export interface DiagramStep {
  icon: string;
  label?: string;
  isArrow?: boolean;
  color?: string;
}

export interface LessonMedia {
  imageUrl: string;
  emoji: string;
  simpleSummary: string;
  keyFacts: string[];
  funFact: string;
  diagramSteps: DiagramStep[];
}

const B = "https://images.unsplash.com/photo-";
const Q = "?w=800&fit=crop";
const u = (id: string) => `${B}${id}${Q}`;

const LESSON_MEDIA: Record<string, Record<number, LessonMedia>> = {
  "Math Adventures": {
    1: {
      imageUrl: u("1635070041078-e363dbe005cb"),
      emoji: "➕",
      simpleSummary: "Addition means putting two groups together to find out how many there are in total!",
      keyFacts: [
        "2 + 3 means you have 2 things, then you add 3 more — now you have 5! 🎉",
        "When you add 0 to any number, the number stays the same (5 + 0 = 5).",
        "You can add numbers in any order: 3 + 4 is the same as 4 + 3.",
        "Adding is like counting forward on a number line ➡️",
      ],
      funFact: "🌟 Every time you count objects, you're already using addition!",
      diagramSteps: [
        { icon: "🍎🍎", label: "Start:\n2 apples" },
        { icon: "➕", label: "ADD\n(put together)" },
        { icon: "🍎🍎🍎", label: "Add 3 more\napples" },
        { icon: "=", label: "EQUALS\n(the result)" },
        { icon: "🍎×5", label: "Total: 5\napples! 🎉", color: "green" },
        { icon: "💡", label: "Real life:\ncounting toys!" },
      ],
    },
    2: {
      imageUrl: u("1509228627152-72ae9ae6848d"),
      emoji: "➖",
      simpleSummary: "Subtraction is finding out how many are left when you take some away!",
      keyFacts: [
        "7 – 3 means: start with 7, take away 3, you have 4 left 🐘",
        "When you subtract 0, nothing changes (8 – 0 = 8).",
        "Subtraction is the opposite of addition — they undo each other!",
        "Subtracting on a number line means moving backwards ⬅️",
      ],
      funFact: "🌟 If you eat 3 cookies from a pack of 10, you have 7 left — that's subtraction!",
      diagramSteps: [
        { icon: "🍪×10", label: "Start:\n10 cookies" },
        { icon: "➖", label: "MINUS\n(take away)" },
        { icon: "🍪×3", label: "Eat 3\ncookies 😋" },
        { icon: "=", label: "EQUALS\n(what's left)" },
        { icon: "🍪×7", label: "7 cookies\nremain! ✅", color: "green" },
        { icon: "⬅️", label: "Number line:\nmove backwards!" },
      ],
    },
    3: {
      imageUrl: u("1518133910546-b6c2fb7d79e3"),
      emoji: "✖️",
      simpleSummary: "Multiplication is a fast way to add the same number over and over again!",
      keyFacts: [
        "3 × 4 means adding 3 four times: 3 + 3 + 3 + 3 = 12 🚀",
        "Any number times 1 stays the same (5 × 1 = 5).",
        "Any number times 0 equals 0 (99 × 0 = 0).",
        "The order doesn't matter: 2 × 6 = 6 × 2 = 12.",
      ],
      funFact: "🌟 If 4 friends each have 3 balloons, that's 4 × 3 = 12 balloons total!",
      diagramSteps: [
        { icon: "🎈🎈🎈", label: "3 balloons\nper friend" },
        { icon: "✖️", label: "TIMES\n(groups of)" },
        { icon: "👧👦👧👦", label: "4 friends\n(4 groups)" },
        { icon: "=", label: "EQUALS" },
        { icon: "🎈×12", label: "12 balloons\ntotal! 🎉", color: "green" },
        { icon: "🔢", label: "Times tables:\nlearn them all!" },
      ],
    },
    4: {
      imageUrl: u("1596495577886-d920f1fb7238"),
      emoji: "➗",
      simpleSummary: "Division means splitting a group into equal parts to see how many each part gets!",
      keyFacts: [
        "12 ÷ 3 = 4 means 12 things split into 3 equal groups gives 4 each 🍕",
        "Division is the opposite of multiplication.",
        "Any number divided by 1 stays the same (9 ÷ 1 = 9).",
        "You can't divide by zero — it doesn't make sense in math!",
      ],
      funFact: "🌟 Sharing 8 candies equally with 4 friends? That's 8 ÷ 4 = 2 each!",
      diagramSteps: [
        { icon: "🍕×12", label: "12 pizza\nslices total" },
        { icon: "➗", label: "DIVIDE\n(split fairly)" },
        { icon: "👧👦👧👦", label: "4 friends\nsharing" },
        { icon: "=", label: "EQUALS" },
        { icon: "🍕🍕🍕", label: "3 slices\neach! ✅", color: "green" },
        { icon: "⚠️", label: "Can't divide\nby zero!" },
      ],
    },
    5: {
      imageUrl: u("1513151233558-d860c5398176"),
      emoji: "🍕",
      simpleSummary: "Fractions show parts of a whole — like slices of pizza!",
      keyFacts: [
        "1/2 means one part out of two equal pieces 🍕",
        "The number on top (numerator) tells how many parts you have.",
        "The number on bottom (denominator) tells how many total equal parts.",
        "1/4 + 1/4 + 1/4 + 1/4 = 1 whole!",
      ],
      funFact: "🌟 When you eat half a pizza, you ate 1/2 of it — that's a fraction!",
      diagramSteps: [
        { icon: "🟡", label: "1 Whole\ncircle" },
        { icon: "🟡🟡", label: "1/2 + 1/2\n= 2 halves" },
        { icon: "🟡🟡🟡🟡", label: "1/4 + 1/4 +\n1/4 + 1/4 = 1" },
        { icon: "🍕", label: "Pizza: the\nbest fraction!" },
        { icon: "🔢", label: "Top = how many\nyou HAVE", color: "green" },
        { icon: "📊", label: "Bottom = total\nequal PARTS" },
      ],
    },
    6: {
      imageUrl: u("1588854337115-1c67d9247e4d"),
      emoji: "📐",
      simpleSummary: "Geometry is about shapes — their sides, corners, and how they fit in space!",
      keyFacts: [
        "A triangle has 3 sides and 3 corners 🔺",
        "A square has 4 equal sides and 4 square corners.",
        "A circle has no sides — it's a perfect round shape ⭕",
        "Shapes are everywhere: books are rectangles, clocks are circles!",
      ],
      funFact: "🌟 Honeybees build their honeycombs in perfect hexagons — 6 sides each!",
      diagramSteps: [
        { icon: "🔺", label: "Triangle\n3 sides, 3 corners" },
        { icon: "⬛", label: "Square\n4 equal sides" },
        { icon: "🔷", label: "Diamond\n4 sides" },
        { icon: "⭕", label: "Circle\nNo sides at all!" },
        { icon: "⬡", label: "Hexagon\n6 sides (bee!)", color: "green" },
        { icon: "🌍", label: "Shapes hide\neverywhere!" },
      ],
    },
    7: {
      imageUrl: u("1611532736597-de2d4265fba3"),
      emoji: "📏",
      simpleSummary: "Measurement helps us compare sizes, weights, and distances!",
      keyFacts: [
        "We use centimeters (cm) and meters (m) to measure length 📏",
        "1 meter = 100 centimeters. A door is about 2 meters tall!",
        "Kilograms (kg) measure how heavy something is.",
        "Liters measure how much liquid fits in a container.",
      ],
      funFact: "🌟 Your thumb is about 1 centimeter wide — that's how ancient people measured inches!",
      diagramSteps: [
        { icon: "📏", label: "Length\ncm and m" },
        { icon: "⚖️", label: "Weight\ng and kg" },
        { icon: "🥤", label: "Volume\nmL and L" },
        { icon: "🌡️", label: "Temperature\n°C and °F" },
        { icon: "⏱️", label: "Time\nsec, min, hr", color: "green" },
        { icon: "🧮", label: "Measure to\ncompare & build!" },
      ],
    },
    8: {
      imageUrl: u("1570295999919-56ceb5ecca61"),
      emoji: "🔢",
      simpleSummary: "Number patterns are sequences that follow a rule — can you find it?",
      keyFacts: [
        "2, 4, 6, 8… this pattern adds 2 each time (even numbers!).",
        "1, 3, 9, 27… this pattern multiplies by 3 each time.",
        "Patterns are everywhere: tiles, music, and even nature!",
        "Finding the rule lets you predict what comes next.",
      ],
      funFact: "🌟 The Fibonacci sequence (1, 1, 2, 3, 5, 8, 13…) appears in sunflowers and seashells!",
      diagramSteps: [
        { icon: "2, 4, 6, 8", label: "+2 each time\n(even numbers)" },
        { icon: "1, 3, 9, 27", label: "×3 each time\n(exponential!)" },
        { icon: "🔴🔵🔴🔵", label: "Color patterns\nrepeat!" },
        { icon: "1,1,2,3,5,8", label: "Fibonacci:\nadd two before!" },
        { icon: "🌻🐚", label: "Fibonacci in\nnature! 🌟", color: "green" },
        { icon: "❓", label: "Spot the rule\n→ predict next!" },
      ],
    },
    9: {
      imageUrl: u("1503676260728-1c00da094a0b"),
      emoji: "🧩",
      simpleSummary: "Word problems use math to solve real-life situations — read carefully!",
      keyFacts: [
        "First, find the numbers in the problem. Then decide: add, subtract, multiply, or divide?",
        "Draw a picture or diagram to help visualize the problem 🖼️",
        "Keywords: 'in all' / 'total' → add; 'left over' → subtract; 'each' → multiply or divide.",
        "Always check your answer by reading the question again!",
      ],
      funFact: "🌟 Ancient Egyptians used word problems 4,000 years ago to build pyramids!",
      diagramSteps: [
        { icon: "📖", label: "Step 1:\nRead carefully" },
        { icon: "🔍", label: "Step 2:\nFind the numbers" },
        { icon: "💡", label: "Step 3:\nChoose +−×÷" },
        { icon: "✏️", label: "Step 4:\nSolve it!" },
        { icon: "✅", label: "Step 5:\nCheck your answer", color: "green" },
        { icon: "🏆", label: "Practice =\nmath champion!" },
      ],
    },
    10: {
      imageUrl: u("1580582932707-520aed937b7b"),
      emoji: "⚡",
      simpleSummary: "Mental math lets you solve problems fast — right in your head!",
      keyFacts: [
        "To add 9, first add 10, then subtract 1. (47 + 9 → 47 + 10 – 1 = 56).",
        "Doubles are easy: 7 + 7 = 14, 8 + 8 = 16 — learn them!",
        "Round to the nearest 10 for quick estimates.",
        "Practice makes you faster — even 5 minutes a day helps!",
      ],
      funFact: "🌟 Mental math champions can multiply 7-digit numbers in their heads!",
      diagramSteps: [
        { icon: "47+9=?", label: "Hard problem" },
        { icon: "47+10=57", label: "Trick: add 10\nfirst!" },
        { icon: "57−1=56", label: "Subtract 1\n= answer ⚡" },
        { icon: "2×2=4", label: "Know doubles:\n2×2, 3×3, 4×4" },
        { icon: "🔟", label: "Round to 10:\nfor estimates", color: "green" },
        { icon: "🏅", label: "5 min/day\n= superstar!" },
      ],
    },
  },

  "Science Explorer": {
    1: {
      imageUrl: u("1504192010706-dd7f569ee2be"),
      emoji: "💧",
      simpleSummary: "Water travels from oceans to clouds to rain and back again — it never stops!",
      keyFacts: [
        "Evaporation: The sun heats water, turning it into invisible water vapor ☀️",
        "Condensation: Water vapor cools and forms tiny droplets → clouds ☁️",
        "Precipitation: Water falls back as rain, snow, or hail 🌧️",
        "Collection: Water flows back into rivers, lakes, and oceans 🌊",
      ],
      funFact: "🌟 The same water that dinosaurs drank millions of years ago is still cycling around our planet today!",
      diagramSteps: [
        { icon: "☀️", label: "Sun heats\nocean water" },
        { icon: "💨↑", label: "Evaporation:\nwater rises up" },
        { icon: "☁️", label: "Condensation:\nclouds form" },
        { icon: "🌧️", label: "Precipitation:\nrain falls down" },
        { icon: "🌊", label: "Collection:\nback to ocean!", color: "blue" },
        { icon: "♻️", label: "Never-ending\ncycle! 🌍" },
      ],
    },
    2: {
      imageUrl: u("1559825481-12a05cc00344"),
      emoji: "🧊",
      simpleSummary: "Matter can be solid, liquid, or gas — and it can change between them!",
      keyFacts: [
        "Solid: particles are tightly packed — keeps its shape (ice, rock, wood) 🪨",
        "Liquid: particles flow — takes the shape of its container (water, juice) 💧",
        "Gas: particles spread out freely — fills all available space (air, steam) 💨",
        "Heat causes matter to melt or evaporate; cold causes it to freeze.",
      ],
      funFact: "🌟 Dry ice is solid CO₂ that turns directly into gas — it skips the liquid state!",
      diagramSteps: [
        { icon: "🧊", label: "Solid:\nparticles locked tight" },
        { icon: "🔥→", label: "ADD HEAT:\nmelting point!" },
        { icon: "💧", label: "Liquid:\nparticles flow" },
        { icon: "🔥→", label: "MORE HEAT:\nboiling point!" },
        { icon: "💨", label: "Gas:\nparticles fly free!", color: "green" },
        { icon: "❄️←", label: "COOLING reverses\neverything!" },
      ],
    },
    3: {
      imageUrl: u("1416879595882-3373a0480b5b"),
      emoji: "🌱",
      simpleSummary: "Plants grow from tiny seeds and make their own food using sunlight!",
      keyFacts: [
        "Germination: A seed sprouts when it has water, warmth, and oxygen 🌱",
        "Photosynthesis: Leaves use sunlight + water + CO₂ to make food + oxygen ☀️",
        "Roots absorb water and nutrients from the soil.",
        "Flowers help the plant reproduce — they attract bees and butterflies 🌸",
      ],
      funFact: "🌟 The world's tallest tree (a redwood) is taller than a 35-story building!",
      diagramSteps: [
        { icon: "🌰", label: "Tiny seed\nin the soil" },
        { icon: "💧+🌡️", label: "Water + warmth\n= germination" },
        { icon: "🌱", label: "Sprout breaks\nthrough soil!" },
        { icon: "☀️+💧+🌿", label: "Photosynthesis:\nsunlight makes food" },
        { icon: "🌸", label: "Flowers bloom\n& make seeds!", color: "green" },
        { icon: "🌳", label: "Fully grown:\ncan live 1000 yrs!" },
      ],
    },
    4: {
      imageUrl: u("1474511320723-9a56873867b5"),
      emoji: "🦁",
      simpleSummary: "Every animal lives in a habitat perfectly suited to its needs!",
      keyFacts: [
        "Desert animals store water and stay cool (camels, lizards) 🐪",
        "Ocean animals breathe through gills and have streamlined bodies 🐟",
        "Forest animals use camouflage to hide in trees and leaves 🦎",
        "A habitat provides food, water, shelter, and space 🏠",
      ],
      funFact: "🌟 Polar bears have black skin under their white fur — it helps absorb heat from the sun!",
      diagramSteps: [
        { icon: "🐪", label: "Desert:\nhot, dry, water storage" },
        { icon: "🐟", label: "Ocean:\ngills breathe water" },
        { icon: "🦁", label: "Savanna:\nwarm, grassy, hunting" },
        { icon: "🐻", label: "Forest:\ncool, shady, berries" },
        { icon: "🐧", label: "Polar:\niceberg & blubber!", color: "blue" },
        { icon: "🌍", label: "Protecting habitats\nsaves species!" },
      ],
    },
    5: {
      imageUrl: u("1581091226825-a6a2a5aee158"),
      emoji: "⚙️",
      simpleSummary: "Simple machines make work easier by changing the direction or size of a force!",
      keyFacts: [
        "Lever: a bar that pivots on a fulcrum — teeter-totters and crowbars 🪨",
        "Wheel & Axle: makes it easier to roll heavy things — cars and wagons 🚗",
        "Pulley: uses a rope and wheel to lift heavy loads — flagpoles 🚩",
        "Inclined Plane: a ramp makes it easier to move things up ⛰️",
      ],
      funFact: "🌟 Ancient Egyptians built the pyramids using simple machines — ramps, sleds, and levers!",
      diagramSteps: [
        { icon: "🔧", label: "Lever:\nseesaw & crowbar" },
        { icon: "🎡", label: "Wheel & Axle:\ncart & bicycle" },
        { icon: "🏗️", label: "Pulley:\nflagpole & crane" },
        { icon: "📐", label: "Ramp (Inclined\nPlane): slide" },
        { icon: "🔩", label: "Screw:\nbolt & jar lid", color: "green" },
        { icon: "🔪", label: "Wedge:\naxe & knife!" },
      ],
    },
    6: {
      imageUrl: u("1518152006812-edab29b069ac"),
      emoji: "⚡",
      simpleSummary: "Electricity is the flow of tiny particles called electrons through a wire!",
      keyFacts: [
        "Electrons flow from negative (–) to positive (+) in a circuit ⚡",
        "A circuit must be complete (no gaps) for electricity to flow.",
        "Conductors (copper, iron) let electricity through; insulators (rubber, plastic) block it.",
        "Batteries push electrons using chemical energy 🔋",
      ],
      funFact: "🌟 Lightning is electricity jumping from clouds to the ground — a single bolt has 1 billion volts!",
      diagramSteps: [
        { icon: "🔋", label: "Battery:\nchemical → electric" },
        { icon: "⚡→", label: "Electrons flow\nthrough wire" },
        { icon: "💡", label: "Bulb:\nelectricity → light!" },
        { icon: "🔵", label: "Conductor:\ncopper lets it flow" },
        { icon: "🔴", label: "Insulator:\nrubber blocks it!", color: "green" },
        { icon: "⚡🌩️", label: "Lightning:\n1 billion volts!" },
      ],
    },
    7: {
      imageUrl: u("1451187580459-43490279c0fa"),
      emoji: "🌍",
      simpleSummary: "Earth has layers — like a hard-boiled egg — each with its own properties!",
      keyFacts: [
        "Crust: the thin outer layer we live on (0–70 km deep) 🗻",
        "Mantle: hot, slow-moving rock below the crust (~2,900 km thick) 🌋",
        "Outer Core: liquid iron and nickel that creates Earth's magnetic field.",
        "Inner Core: solid iron ball, incredibly hot (about 5,000°C!) 🔥",
      ],
      funFact: "🌟 The Earth's crust is only about 1% of its total volume — most of Earth is the mantle!",
      diagramSteps: [
        { icon: "🟤", label: "Crust:\n0-70 km deep" },
        { icon: "🔴", label: "Mantle:\nhot slow rock" },
        { icon: "🟠", label: "Outer Core:\nliquid iron!" },
        { icon: "⭕", label: "Inner Core:\nsolid + 5000°C" },
        { icon: "🧲", label: "Core creates\nEarth's magnetism!", color: "green" },
        { icon: "🌋", label: "Volcanoes:\nmantle erupts up!" },
      ],
    },
    8: {
      imageUrl: u("1454789548928-9efd52dc4031"),
      emoji: "🌕",
      simpleSummary: "The Moon orbits Earth, and Earth orbits the Sun — our solar system is enormous!",
      keyFacts: [
        "Earth takes 365 days (1 year) to orbit the Sun ☀️",
        "The Moon takes about 29 days to orbit Earth 🌕",
        "Gravity is the force that keeps planets in orbit.",
        "Our solar system has 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
      ],
      funFact: "🌟 If Earth were the size of a grape, the Sun would be as big as a 6-story building!",
      diagramSteps: [
        { icon: "☀️", label: "Sun:\ncenter of solar system" },
        { icon: "🌍", label: "Earth orbits Sun\nin 365 days" },
        { icon: "🌕", label: "Moon orbits Earth\nin 29 days" },
        { icon: "🚀", label: "Gravity keeps\neveryone in orbit" },
        { icon: "🪐", label: "8 planets total\nin our system!", color: "green" },
        { icon: "🌌", label: "Humans walked\non the Moon 1969!" },
      ],
    },
    9: {
      imageUrl: u("1519681393784-d120267933ba"),
      emoji: "🌡️",
      simpleSummary: "Weather is what's happening in the atmosphere right now — it changes every day!",
      keyFacts: [
        "Temperature measures how hot or cold the air is 🌡️",
        "Wind is caused by warm air rising and cool air rushing in.",
        "Clouds form when water vapor condenses around tiny dust particles ☁️",
        "Meteorologists use satellites, radar, and weather stations to forecast weather 📡",
      ],
      funFact: "🌟 A tornado's wind can spin faster than 300 mph — faster than a race car!",
      diagramSteps: [
        { icon: "☀️", label: "Sunny:\nhigh pressure, clear" },
        { icon: "⛅", label: "Cloudy:\nwater vapor rises" },
        { icon: "🌧️", label: "Rainy:\ncloud droplets fall" },
        { icon: "❄️", label: "Snowy:\nfreezing precipitation" },
        { icon: "🌪️", label: "Tornado:\n300 mph winds!", color: "green" },
        { icon: "🌈", label: "Rainbow:\nafter sun+rain!" },
      ],
    },
    10: {
      imageUrl: u("1532094349884-543290648cca"),
      emoji: "🧫",
      simpleSummary: "The human body is made of trillions of tiny cells working together like a team!",
      keyFacts: [
        "Cells are the smallest unit of life — too tiny to see without a microscope 🔬",
        "Heart cells pump blood; nerve cells carry messages; muscle cells move your body.",
        "Red blood cells carry oxygen from lungs to every part of your body 🩸",
        "Your body makes millions of new cells every second!",
      ],
      funFact: "🌟 You have about 37 trillion cells in your body — more than all the stars in the Milky Way!",
      diagramSteps: [
        { icon: "🫀", label: "Heart cells:\npump blood" },
        { icon: "🧠", label: "Nerve cells:\ncarry signals" },
        { icon: "💪", label: "Muscle cells:\ncreate movement" },
        { icon: "🩸", label: "Red blood cells:\ncarry oxygen" },
        { icon: "🛡️", label: "White blood cells:\nfight germs!", color: "green" },
        { icon: "🔬", label: "37 trillion cells\nin YOUR body!" },
      ],
    },
  },

  "Reading & Writing Stars": {
    1: {
      imageUrl: u("1481627834876-b7833e8f5570"),
      emoji: "📖",
      simpleSummary: "Every story has characters, a setting, a problem, and a solution!",
      keyFacts: [
        "Characters: the people or animals the story is about 🧑",
        "Setting: where and when the story takes place (a forest, in the past) 🌲",
        "Plot: the events that happen — beginning, middle, end 📚",
        "Theme: the big message or lesson the author wants you to learn.",
      ],
      funFact: "🌟 The world's longest novel has 1.5 million words — about 9,000 pages!",
      diagramSteps: [
        { icon: "🧑", label: "Characters:\nWHO is the story?" },
        { icon: "🌲", label: "Setting:\nWHERE & WHEN?" },
        { icon: "⚡", label: "Problem:\nWHAT goes wrong?" },
        { icon: "🔥", label: "Climax:\nbiggest moment!" },
        { icon: "🌈", label: "Solution:\nHOW it ends!", color: "green" },
        { icon: "💡", label: "Theme:\nthe BIG lesson!" },
      ],
    },
    2: {
      imageUrl: u("1456513080510-7bf3a84b82f8"),
      emoji: "🧠",
      simpleSummary: "Good readers ask questions, make predictions, and connect ideas to understand text!",
      keyFacts: [
        "Main idea: the most important point the text is making 💡",
        "Supporting details: facts and examples that explain the main idea.",
        "Make inferences: use clues + what you know to figure out what's not directly stated.",
        "Summarize: put the key ideas in your own words after reading.",
      ],
      funFact: "🌟 Speed readers can read 1,000+ words per minute — that's a page every 30 seconds!",
      diagramSteps: [
        { icon: "📖", label: "Before:\npredict the topic" },
        { icon: "❓", label: "During:\nask questions!" },
        { icon: "💡", label: "Find:\nmain idea" },
        { icon: "🧩", label: "Connect:\nsupporting details" },
        { icon: "✍️", label: "Summarize:\nin YOUR words", color: "green" },
        { icon: "🔁", label: "Re-read tough\nparts again!" },
      ],
    },
    3: {
      imageUrl: u("1455390582262-044cdead277a"),
      emoji: "✍️",
      simpleSummary: "Good writing has a beginning (hook), middle (details), and end (conclusion)!",
      keyFacts: [
        "Hook: start with something interesting to grab the reader's attention! 🎣",
        "Body paragraphs: each one has a main idea + 2-3 supporting details.",
        "Conclusion: wrap up your ideas and leave the reader thinking.",
        "Revise and edit: always re-read your writing to make it better! ✏️",
      ],
      funFact: "🌟 J.K. Rowling wrote Harry Potter on paper napkins in a café before she could afford a computer!",
      diagramSteps: [
        { icon: "🎣", label: "Hook:\ngrab attention!" },
        { icon: "📄", label: "Para 1:\nfirst main idea" },
        { icon: "📄", label: "Para 2:\nsecond idea" },
        { icon: "📄", label: "Para 3:\nthird idea" },
        { icon: "🏁", label: "Conclusion:\nwrap it up!", color: "green" },
        { icon: "✂️", label: "Edit:\ncut weak words!" },
      ],
    },
    4: {
      imageUrl: u("1503676260728-1c00da094a0b"),
      emoji: "🔤",
      simpleSummary: "Grammar rules help us write clearly so readers can understand exactly what we mean!",
      keyFacts: [
        "Noun: a person, place, thing, or idea (cat, school, happiness) 🐱",
        "Verb: an action or state of being (run, is, think) 🏃",
        "Adjective: describes a noun (big, blue, happy) 🎨",
        "A sentence needs at least a subject (noun) and a predicate (verb) to be complete.",
      ],
      funFact: "🌟 The sentence 'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo' is grammatically correct English!",
      diagramSteps: [
        { icon: "🐱", label: "Noun:\ncat, school, idea" },
        { icon: "🏃", label: "Verb:\nrun, jump, think" },
        { icon: "🎨", label: "Adjective:\nbig, blue, happy" },
        { icon: "📍", label: "Adverb:\nquickly, very" },
        { icon: "🔗", label: "Conjunction:\nand, but, or", color: "green" },
        { icon: "✅", label: "= A complete\nperfect sentence!" },
      ],
    },
    5: {
      imageUrl: u("1571019613454-1cb2f99b2d8b"),
      emoji: "🔡",
      simpleSummary: "Spelling tricks help you remember tricky words — patterns make spelling easier!",
      keyFacts: [
        "i before e except after c (receive, believe) — but there are exceptions!",
        "Silent letters: the 'k' in 'know', the 'b' in 'climb', the 'w' in 'write' 🤫",
        "Compound words: two words join to make one (sunshine = sun + shine) ☀️",
        "Prefixes and suffixes: un + happy = unhappy; play + ful = playful.",
      ],
      funFact: "🌟 The word 'queue' is 80% silent — you only pronounce the letter 'q'!",
      diagramSteps: [
        { icon: "sun+shine", label: "Compound words:\n= sunshine ☀️" },
        { icon: "un+happy", label: "Prefix 'un'\n= unhappy" },
        { icon: "play+ful", label: "Suffix 'ful'\n= playful!" },
        { icon: "🤫 k-now", label: "Silent letters:\nknow, lamb, write" },
        { icon: "i before e", label: "Rule: believe,\nreceive", color: "green" },
        { icon: "🏆", label: "10 words/day\n= expert speller!" },
      ],
    },
    6: {
      imageUrl: u("1516979187457-637abb4f9353"),
      emoji: "🗣️",
      simpleSummary: "Vocabulary means knowing lots of words — the more you know, the better you read and write!",
      keyFacts: [
        "Context clues: use nearby words in the sentence to guess a word's meaning 🕵️",
        "Synonyms: words with similar meanings (big, large, huge).",
        "Antonyms: words with opposite meanings (hot ↔ cold, fast ↔ slow) 🔄",
        "Root words: 'port' means carry → transport, import, export.",
      ],
      funFact: "🌟 Shakespeare invented over 1,700 English words we still use today — including 'bedroom' and 'lonely'!",
      diagramSteps: [
        { icon: "🔥↔️🧊", label: "Antonyms:\nhot ↔ cold" },
        { icon: "big≈large", label: "Synonyms:\nbig = large = huge" },
        { icon: "port→", label: "Root 'port':\ntransport, import" },
        { icon: "🕵️", label: "Context clues:\nguess from sentence" },
        { icon: "📈", label: "5 new words\nper day!", color: "green" },
        { icon: "📚", label: "Read books:\nbest vocabulary boost!" },
      ],
    },
    7: {
      imageUrl: u("1478720568477-152d9b164e26"),
      emoji: "🎭",
      simpleSummary: "Poetry uses rhythm, rhyme, and vivid images to express feelings and ideas!",
      keyFacts: [
        "Rhyme: words that end with the same sound (cat/hat, moon/tune) 🌙",
        "Rhythm: the beat or flow of words in a poem — like music!",
        "Simile: comparing using 'like' or 'as' (as fast as lightning ⚡)",
        "Metaphor: saying something IS something else (life is a rollercoaster 🎢)",
      ],
      funFact: "🌟 The shortest poem ever is 'Fleas / Adam / Had'em' — just 6 syllables!",
      diagramSteps: [
        { icon: "🌙 tune June", label: "Rhyme:\nsame end sound" },
        { icon: "🥁 DUM-da", label: "Rhythm:\nbeat of the poem" },
        { icon: "⚡ as fast as", label: "Simile:\ncompare with 'like/as'" },
        { icon: "🎢 life IS", label: "Metaphor:\nsay it IS something" },
        { icon: "🌿", label: "Imagery:\npaint pictures with words!", color: "green" },
        { icon: "✍️", label: "Your turn:\nwrite your own poem!" },
      ],
    },
    8: {
      imageUrl: u("1507842217343-583bb7270b66"),
      emoji: "📰",
      simpleSummary: "Nonfiction writing shares real facts, opinions, and information about the world!",
      keyFacts: [
        "Fact: something that can be proven true (The Eiffel Tower is in Paris ✅)",
        "Opinion: what someone thinks or believes (Paris is the most beautiful city).",
        "Text features: headings, bold words, captions, and diagrams help readers.",
        "Bias: when a writer favors one side — good readers notice this!",
      ],
      funFact: "🌟 The first newspaper was printed in Germany in 1605 — before that, news spread by word of mouth!",
      diagramSteps: [
        { icon: "✅ FACT", label: "Fact:\ncan be proven!" },
        { icon: "💭 OPINION", label: "Opinion:\nwhat I think" },
        { icon: "📋 Headings", label: "Text features:\nheadings, bold, diagrams" },
        { icon: "⚖️", label: "Bias:\ncheck the author's view!" },
        { icon: "🕵️", label: "Read critically:\nfact-check it!", color: "green" },
        { icon: "📊 + 💬", label: "Facts + opinions\n= full picture!" },
      ],
    },
    9: {
      imageUrl: u("1455390582262-044cdead277a"),
      emoji: "🖊️",
      simpleSummary: "Persuasive writing tries to convince the reader to agree with your opinion!",
      keyFacts: [
        "State your opinion clearly at the beginning. 💬",
        "Give 3 strong reasons to support your opinion.",
        "Use evidence: facts, statistics, and examples make arguments stronger 📊",
        "Address the other side (counterargument) and explain why you still disagree.",
      ],
      funFact: "🌟 The most persuasive word in English is 'you' — it makes people feel personally involved!",
      diagramSteps: [
        { icon: "💬", label: "Opinion:\nstate it clearly!" },
        { icon: "1️⃣ Reason", label: "Reason 1:\nstrongest point" },
        { icon: "2️⃣ Evidence", label: "Evidence:\nfacts & examples" },
        { icon: "3️⃣ Reason", label: "Reason 2 &\ncounterargument" },
        { icon: "🏁", label: "Conclusion:\ncall to action!", color: "green" },
        { icon: "YOU!", label: "Magic word:\n'you' convinces!" },
      ],
    },
    10: {
      imageUrl: u("1524578271613-d550eacf6090"),
      emoji: "🌐",
      simpleSummary: "Research skills help you find trustworthy information and use it in your writing!",
      keyFacts: [
        "Reliable sources: encyclopedias, textbooks, .gov and .edu websites 📚",
        "Keywords: use specific search words to find exactly what you need.",
        "Note-taking: write down key ideas in your own words — not copy-paste!",
        "Citation: always credit the author/source of information you use.",
      ],
      funFact: "🌟 Wikipedia has over 60 million articles in 300+ languages!",
      diagramSteps: [
        { icon: "❓", label: "Question:\nwhat do I want to know?" },
        { icon: "🔍", label: "Search:\ngood keywords matter!" },
        { icon: "✅ .edu .gov", label: "Trust:\nreliable sources only" },
        { icon: "📋", label: "Notes:\nin your OWN words" },
        { icon: "📝 Cite", label: "Cite:\ncredit your sources!", color: "green" },
        { icon: "🎓", label: "Research =\nlifelong superpower!" },
      ],
    },
  },

  "World Geography Quest": {
    1: {
      imageUrl: u("1451187580459-43490279c0fa"),
      emoji: "🌍",
      simpleSummary: "Earth has 7 continents and 5 oceans — let's explore them all!",
      keyFacts: [
        "7 Continents: Asia, Africa, North America, South America, Antarctica, Europe, Australia 🗺️",
        "5 Oceans: Pacific (largest), Atlantic, Indian, Southern, Arctic (smallest) 🌊",
        "Asia is the largest continent — it has more than half of all Earth's people!",
        "Antarctica is the coldest, driest, and windiest continent.",
      ],
      funFact: "🌟 The Pacific Ocean is so large you could fit all 7 continents inside it!",
      diagramSteps: [
        { icon: "🌏", label: "Asia:\nlargest continent!" },
        { icon: "🌍", label: "Africa:\n2nd largest" },
        { icon: "🌎", label: "Americas:\nNorth & South" },
        { icon: "🏔️", label: "Europe &\nAustralia" },
        { icon: "🧊", label: "Antarctica:\ncoldest & windiest!", color: "blue" },
        { icon: "🌊×5", label: "5 Oceans:\ncover 71% of Earth!" },
      ],
    },
    2: {
      imageUrl: u("1526778548025-fa2f459cd5c1"),
      emoji: "🏛️",
      simpleSummary: "There are 195 countries in the world, each with its own capital city and flag!",
      keyFacts: [
        "Russia is the world's largest country — it covers 11 time zones! 🇷🇺",
        "Vatican City is the smallest country — it fits inside the city of Rome 🇻🇦",
        "China and India each have over 1 billion people — the most of any country.",
        "Every country has a flag that represents its history and values 🏳️",
      ],
      funFact: "🌟 Monaco is smaller than Central Park in New York City!",
      diagramSteps: [
        { icon: "195", label: "195 countries\nin the world!" },
        { icon: "🇷🇺", label: "Russia:\nlargest, 11 time zones" },
        { icon: "🇻🇦", label: "Vatican City:\ntiniest country!" },
        { icon: "🏙️", label: "Each has a\ncapital city" },
        { icon: "🏳️", label: "Every country\nhas its own flag!", color: "green" },
        { icon: "🤝", label: "195 countries\nshare one planet!" },
      ],
    },
    3: {
      imageUrl: u("1516450360452-9312f5e86fc7"),
      emoji: "🎎",
      simpleSummary: "Every culture around the world has its own unique food, music, clothing, and traditions!",
      keyFacts: [
        "Japan has 'hanami' — people gather to admire cherry blossoms 🌸",
        "India celebrates Diwali, the Festival of Lights, with fireworks and oil lamps 🪔",
        "Brazil's Carnival is one of the world's biggest festivals — millions attend! 🎉",
        "Food tells the story of a culture — spices and recipes passed through generations.",
      ],
      funFact: "🌟 Over 7,000 languages are spoken in the world today!",
      diagramSteps: [
        { icon: "🍜", label: "Asia:\nrice, noodles, spice!" },
        { icon: "🍕", label: "Europe:\nbread, pasta, cheese" },
        { icon: "🌮", label: "Americas:\ncorn, beans, spice" },
        { icon: "🥘", label: "Africa:\nstews, yams, millet" },
        { icon: "🎉", label: "Festivals:\nDiwali, Carnival, Hanami!", color: "green" },
        { icon: "7000+", label: "7,000 languages\nspoken worldwide!" },
      ],
    },
    4: {
      imageUrl: u("1470770903676-69b98201ea1c"),
      emoji: "🌡️",
      simpleSummary: "Different parts of Earth have different climates based on their distance from the equator!",
      keyFacts: [
        "Tropical zone (near equator): hot and rainy all year — home to rainforests 🌴",
        "Temperate zone (middle): 4 seasons — spring, summer, autumn, winter ❄️",
        "Polar zone (near poles): freezing cold all year — ice and tundra 🧊",
        "Climate affects what food people grow and how they build their homes.",
      ],
      funFact: "🌟 The Atacama Desert hasn't had rain in some parts for 400 years!",
      diagramSteps: [
        { icon: "🌴🌡️", label: "Tropical:\nhot & rainy year-round" },
        { icon: "🌸", label: "Temperate:\n4 beautiful seasons" },
        { icon: "🏜️", label: "Arid/Desert:\nhot, bone dry!" },
        { icon: "🌲", label: "Continental:\nsnow winters" },
        { icon: "🧊", label: "Polar:\nfreezing year-round!", color: "blue" },
        { icon: "🌍", label: "Climate shapes\nhow all life lives!" },
      ],
    },
    5: {
      imageUrl: u("1506905925346-21bda4d32df4"),
      emoji: "🏔️",
      simpleSummary: "Earth's natural wonders show the amazing power of nature — from mountains to waterfalls!",
      keyFacts: [
        "Mount Everest (8,849 m) is the highest point on Earth 🏔️",
        "The Great Barrier Reef in Australia is the world's largest living structure 🐠",
        "The Amazon River carries more water than the next 7 largest rivers combined 🌊",
        "The Northern Lights are caused by solar particles hitting Earth's atmosphere ✨",
      ],
      funFact: "🌟 Victoria Falls can be heard 40 km away — that's the sound of nature's power!",
      diagramSteps: [
        { icon: "🏔️", label: "Everest:\n8,849 m high!" },
        { icon: "🌊", label: "Amazon River:\nworld's biggest flow" },
        { icon: "🐠", label: "Great Barrier Reef:\nlargest living thing" },
        { icon: "🌌", label: "Northern Lights:\nsolar+atmosphere" },
        { icon: "🌋", label: "Volcano:\nnature's power!", color: "green" },
        { icon: "📸", label: "Protect these\nwonders forever!" },
      ],
    },
    6: {
      imageUrl: u("1569949381669-ecf31ae8e613"),
      emoji: "🗺️",
      simpleSummary: "Maps are tools that help us understand where places are in relation to each other!",
      keyFacts: [
        "Latitude lines run east-west; they measure how far north/south you are from the equator.",
        "Longitude lines run north-south; they measure how far east/west from the prime meridian.",
        "The equator (0° latitude) divides Earth into Northern and Southern hemispheres.",
        "GPS satellites in space help phones and cars show maps instantly 📡",
      ],
      funFact: "🌟 Ancient maps from 600 BC showed Babylon at the center of the world!",
      diagramSteps: [
        { icon: "↕️", label: "Latitude:\nnorth-south position" },
        { icon: "↔️", label: "Longitude:\neast-west position" },
        { icon: "📍0°", label: "Equator = 0°\ndivides hemispheres" },
        { icon: "📍", label: "Latitude + Longitude\n= exact location!" },
        { icon: "📡", label: "GPS uses\n24 satellites!", color: "green" },
        { icon: "🛰️", label: "Maps update\nin real-time now!" },
      ],
    },
    7: {
      imageUrl: u("1467226632440-65f0b4957563"),
      emoji: "🏙️",
      simpleSummary: "Cities are hubs of culture, trade, and innovation — over half the world's people live in them!",
      keyFacts: [
        "Tokyo, Japan is the world's largest city with over 37 million people! 🗼",
        "Cities develop where there's fresh water, trade routes, or natural resources.",
        "Megacities have 10 million+ people: Mumbai, São Paulo, Mexico City, Cairo 🌆",
        "Urban planning decides how streets, parks, and buildings are organized.",
      ],
      funFact: "🌟 Shanghai's metro carries more passengers daily than the entire US Amtrak does in a year!",
      diagramSteps: [
        { icon: "💧", label: "Cities start:\nnear water sources" },
        { icon: "🏗️", label: "Buildings grow:\nup into the sky" },
        { icon: "🚇", label: "Transport:\nconnects millions" },
        { icon: "🌆", label: "Megacity:\n10M+ people!" },
        { icon: "🗼", label: "Tokyo:\n37 million people!", color: "green" },
        { icon: "🌿", label: "Future cities:\ngreen & sustainable!" },
      ],
    },
    8: {
      imageUrl: u("1464037866556-6812c9d1c72e"),
      emoji: "🌊",
      simpleSummary: "Oceans cover 71% of Earth's surface and are home to the most diverse ecosystems!",
      keyFacts: [
        "The ocean has 5 zones: sunlight, twilight, midnight, abyssal, and hadal zones 🌊",
        "The Mariana Trench is 11 km deep — deeper than Everest is tall!",
        "Coral reefs cover only 1% of the ocean but house 25% of all marine species.",
        "The ocean produces over half the world's oxygen — mostly from tiny phytoplankton.",
      ],
      funFact: "🌟 We've explored less than 20% of Earth's oceans — more people have walked on the Moon!",
      diagramSteps: [
        { icon: "☀️🐠", label: "Sunlight zone:\n0-200 m deep" },
        { icon: "🐙", label: "Twilight zone:\n200-1,000 m" },
        { icon: "🦑", label: "Midnight zone:\n1,000-4,000 m" },
        { icon: "🦐", label: "Abyssal zone:\n4,000-6,000 m" },
        { icon: "⬛", label: "Hadal zone:\n11 km! Mariana!", color: "blue" },
        { icon: "🌊 71%", label: "Oceans =\n71% of Earth!" },
      ],
    },
    9: {
      imageUrl: u("1511632765486-a01980e01a18"),
      emoji: "🌾",
      simpleSummary: "Agriculture feeds the world — how and where food is grown depends on climate and geography!",
      keyFacts: [
        "Fertile soil + water + sunlight = perfect farming conditions 🌾",
        "Rice feeds more people than any other crop — grown in flooded paddies in Asia.",
        "Greenhouses let farmers grow vegetables even in cold climates 🏡",
        "Modern technology (GPS tractors, drones) makes farms more productive.",
      ],
      funFact: "🌟 The Netherlands — one of the world's smallest countries — is the 2nd largest food exporter!",
      diagramSteps: [
        { icon: "☀️", label: "Sunlight:\nplants need energy" },
        { icon: "💧", label: "Water:\nessential for growth" },
        { icon: "🌱", label: "Fertile soil:\nnutrients & minerals" },
        { icon: "🌾", label: "Crops grow:\nrice, wheat, corn!" },
        { icon: "🚜", label: "Harvest:\nGPS tractors & drones!", color: "green" },
        { icon: "🍽️", label: "Food on your\nplate! 🌍" },
      ],
    },
    10: {
      imageUrl: u("1497436072909-60f360e1d4b1"),
      emoji: "♻️",
      simpleSummary: "Earth's resources are precious — we must protect the environment for future generations!",
      keyFacts: [
        "Renewable energy: solar, wind, and hydro power can be used forever ☀️",
        "Deforestation destroys habitats and releases stored CO₂ into the atmosphere 🌳",
        "Recycling reduces waste: 1 tonne of recycled paper saves 17 trees.",
        "Climate change is making storms stronger and sea levels higher 🌊",
      ],
      funFact: "🌟 If everyone lived like the average American, we'd need 5 Earths to support us all!",
      diagramSteps: [
        { icon: "☀️ Solar", label: "Solar energy:\nnever runs out!" },
        { icon: "💨 Wind", label: "Wind energy:\nclean & free!" },
        { icon: "♻️", label: "Recycle:\nsave 17 trees/tonne" },
        { icon: "🌳", label: "Protect forests:\nEarth's lungs!" },
        { icon: "🌊", label: "Rising seas:\nact now!", color: "green" },
        { icon: "🌍💚", label: "Small changes =\nbig impact!" },
      ],
    },
  },

  "Coding for Kids": {
    1: {
      imageUrl: u("1587620962725-abab7fe55159"),
      emoji: "💻",
      simpleSummary: "Programming means giving step-by-step instructions to a computer to solve a problem!",
      keyFacts: [
        "A program is a set of instructions a computer follows exactly as written 📝",
        "Computers do exactly what you tell them — no more, no less!",
        "Programming languages (Python, Scratch, JavaScript) translate human ideas into computer actions.",
        "Bugs are mistakes in code — programmers find and fix them through debugging 🐛",
      ],
      funFact: "🌟 The first computer programmer was Ada Lovelace in 1843 — before computers existed!",
      diagramSteps: [
        { icon: "🧑💡", label: "You:\nhave an idea!" },
        { icon: "✍️", label: "Write code:\nstep-by-step" },
        { icon: "💻", label: "Computer:\nreads code exactly" },
        { icon: "🐛", label: "Bug found:\ndebug & fix!" },
        { icon: "🎯", label: "Problem solved! ✅", color: "green" },
        { icon: "🌍", label: "Code powers\neverything around us!" },
      ],
    },
    2: {
      imageUrl: u("1551288049-bebda4e38f71"),
      emoji: "🔁",
      simpleSummary: "Sequences are steps in order; loops repeat steps automatically to save time!",
      keyFacts: [
        "Sequence: instructions must be in the right order — step 1, then 2, then 3 📋",
        "Loop: repeat a block of code until a condition is met 🔄",
        "For loop: repeat a fixed number of times (do this 10 times).",
        "While loop: keep repeating while something is true (while hungry: eat).",
      ],
      funFact: "🌟 A video game running at 60fps executes its game loop 60 times every second!",
      diagramSteps: [
        { icon: "1️⃣", label: "Wake up\n(step 1)" },
        { icon: "2️⃣", label: "Eat breakfast\n(step 2)" },
        { icon: "3️⃣", label: "Go to school\n(step 3)" },
        { icon: "🔁 for", label: "FOR loop:\nrepeat 10 times" },
        { icon: "🔄 while", label: "WHILE loop:\nrepeat until done!", color: "green" },
        { icon: "🎮×60", label: "Games loop\n60 times/second!" },
      ],
    },
    3: {
      imageUrl: u("1555949963-ff9fe0c870eb"),
      emoji: "🤔",
      simpleSummary: "Conditions let programs make decisions — like 'if it's raining, bring an umbrella'!",
      keyFacts: [
        "IF statement: 'If this is true, do this' — the program decides based on conditions.",
        "ELSE: 'Otherwise, do this other thing instead' 🔀",
        "Comparison operators: == (equals), > (greater than), < (less than) ⚖️",
        "Boolean: a value that's either TRUE or FALSE — computers love true/false!",
      ],
      funFact: "🌟 All complex AI decisions boil down to thousands of if-else conditions!",
      diagramSteps: [
        { icon: "🌧️?", label: "IF: is it\nraining?" },
        { icon: "☂️", label: "TRUE: bring\nan umbrella" },
        { icon: "🕶️", label: "FALSE (ELSE):\nwear sunglasses" },
        { icon: "== > <", label: "Operators:\ncompare values" },
        { icon: "✅❌", label: "Boolean:\nTRUE or FALSE!", color: "green" },
        { icon: "🤖", label: "AI uses millions\nof if-else!" },
      ],
    },
    4: {
      imageUrl: u("1562813733-b31f71025d54"),
      emoji: "📦",
      simpleSummary: "Variables are like labeled boxes that store information a program can use later!",
      keyFacts: [
        "Variable: a named storage location (score = 0; name = 'Alex') 📦",
        "You can change what's in a variable: score = score + 10.",
        "Data types: numbers (42), text/strings ('hello'), true/false (booleans).",
        "Good variable names describe what they hold: playerScore, not x!",
      ],
      funFact: "🌟 Minecraft uses millions of variables to track every block and creature!",
      diagramSteps: [
        { icon: "📦 name", label: "String box:\nname = 'Alex'" },
        { icon: "📦 score", label: "Number box:\nscore = 0" },
        { icon: "📦 isAlive", label: "Boolean box:\nisAlive = TRUE" },
        { icon: "score+10", label: "Update box:\nscore = 10!" },
        { icon: "🎮", label: "Minecraft:\nmillions of boxes!", color: "green" },
        { icon: "✍️", label: "Good names:\nplayerScore > x" },
      ],
    },
    5: {
      imageUrl: u("1498050108023-c5249f4df085"),
      emoji: "🎮",
      simpleSummary: "Functions are reusable blocks of code — write once, use many times!",
      keyFacts: [
        "Function: a named block of code that does one specific task 🧩",
        "Call a function by its name to run its code: jump(); or moveRight();",
        "Functions can accept inputs (parameters) and send back results (return values).",
        "Good functions do ONE thing and do it well.",
      ],
      funFact: "🌟 Your phone's operating system has millions of functions all working together!",
      diagramSteps: [
        { icon: "📝", label: "Define:\nmakeJuice() once" },
        { icon: "🥤", label: "Call it:\nmakeJuice() → juice!" },
        { icon: "🥤", label: "Call again:\nmakeJuice() → juice!" },
        { icon: "📥 📤", label: "Parameters &\nreturn values" },
        { icon: "🧩", label: "One function,\none job! ✅", color: "green" },
        { icon: "📱×M", label: "Your phone:\nmillions of functions!" },
      ],
    },
    6: {
      imageUrl: u("1614741118887-7a4ee193a5fa"),
      emoji: "🌐",
      simpleSummary: "The internet connects billions of computers around the world to share information instantly!",
      keyFacts: [
        "Data travels as packets — small chunks sent separately and reassembled 📦",
        "IP address: a unique number that identifies every device on the internet.",
        "HTML builds the structure of web pages; CSS makes them look pretty 🎨",
        "Servers are powerful computers that store and send websites when you visit them.",
      ],
      funFact: "🌟 Every minute, humans upload 500 hours of video to YouTube and send 300 million emails!",
      diagramSteps: [
        { icon: "🖥️ You", label: "You type\na website URL" },
        { icon: "📦×packets", label: "Request split\ninto packets" },
        { icon: "🌐", label: "Travels through\nthe internet" },
        { icon: "🖥️ Server", label: "Server sends\nwebsite back" },
        { icon: "🔒 HTTPS", label: "Encryption:\nkeeps you safe!", color: "green" },
        { icon: "500hrs/min", label: "YouTube: 500 hrs\nuploaded per minute!" },
      ],
    },
    7: {
      imageUrl: u("1485827404703-89b55fcc595e"),
      emoji: "🤖",
      simpleSummary: "Artificial Intelligence teaches computers to learn from data and make smart decisions!",
      keyFacts: [
        "Machine learning: computers improve through practice with lots of data 📊",
        "Neural networks: inspired by how the human brain processes information 🧠",
        "AI can recognize faces, translate languages, and beat humans at chess.",
        "The more data AI trains on, the more accurate it becomes.",
      ],
      funFact: "🌟 AlphaGo learned to play Go by studying 30 million moves — then beat the world champion!",
      diagramSteps: [
        { icon: "📊", label: "Data:\nfeed AI examples" },
        { icon: "🧠", label: "Neural network:\nfinds patterns" },
        { icon: "✅", label: "Prediction:\nmakes smart choice" },
        { icon: "📈", label: "Gets smarter:\nwith more data!" },
        { icon: "🤖", label: "AI can:\ntranslate, see, chat!", color: "green" },
        { icon: "♟️×30M", label: "AlphaGo studied\n30M chess moves!" },
      ],
    },
    8: {
      imageUrl: u("1518770660439-4636190af475"),
      emoji: "🔒",
      simpleSummary: "Cybersecurity protects computers and information from hackers and bad actors!",
      keyFacts: [
        "Strong passwords use uppercase, lowercase, numbers, and symbols 🔐",
        "Encryption scrambles data so only authorized people can read it.",
        "Phishing: fake emails or websites that trick you into giving away private info 🎣",
        "Always update software — patches fix security holes that hackers exploit.",
      ],
      funFact: "🌟 Over 2,000 cyberattacks happen every day — one attack every 39 seconds somewhere!",
      diagramSteps: [
        { icon: "😈", label: "Hacker:\ntries to steal data" },
        { icon: "🔐", label: "Strong password:\nblocks them!" },
        { icon: "🔒 Encrypt", label: "Encryption:\nscrambles data" },
        { icon: "🎣", label: "Phishing:\nfake emails — avoid!" },
        { icon: "🔄", label: "Update software:\nfix security holes!", color: "green" },
        { icon: "2000/day", label: "2,000 attacks\nhappen every day!" },
      ],
    },
    9: {
      imageUrl: u("1504639725590-34d0984388bd"),
      emoji: "📱",
      simpleSummary: "Apps are programs designed to run on specific devices — making computers useful for everyone!",
      keyFacts: [
        "App = application — a program built for a specific purpose (camera, maps, games) 📱",
        "Mobile apps run on phones; web apps run in browsers; desktop apps on computers.",
        "The App Store and Google Play each have over 3 million apps available!",
        "App development: design → code → test → launch → improve based on feedback.",
      ],
      funFact: "🌟 Instagram was built by 13 people and sold to Facebook for $1 billion just 18 months after launch!",
      diagramSteps: [
        { icon: "💡", label: "Idea:\nwhat problem to solve?" },
        { icon: "🎨", label: "Design:\ndraw all the screens" },
        { icon: "💻", label: "Code:\nbuild the app!" },
        { icon: "🐛", label: "Test:\nfix all the bugs" },
        { icon: "🚀", label: "Launch:\npeople use it! 🎉", color: "green" },
        { icon: "1B$", label: "Instagram sold\nfor $1 billion!" },
      ],
    },
    10: {
      imageUrl: u("1519389950473-47ba0277781c"),
      emoji: "🚀",
      simpleSummary: "Your first project! Put it all together — variables, loops, conditions, and functions!",
      keyFacts: [
        "Start small: a simple game might just need 50 lines of code! 🎮",
        "Plan first: sketch out what you want to build before writing code 📝",
        "Test often: run your code after every small change to catch bugs early.",
        "Share your work: showing others your project helps you improve!",
      ],
      funFact: "🌟 Minecraft was created by just one person and became one of the best-selling games ever!",
      diagramSteps: [
        { icon: "📝", label: "Plan:\nsketch your idea" },
        { icon: "📦🔁", label: "Variables\n& loops" },
        { icon: "🤔✅", label: "Conditions\n& functions" },
        { icon: "🐛", label: "Debug:\ntest often!" },
        { icon: "🚀", label: "Launch your\nfirst project! 🎉", color: "green" },
        { icon: "🌟", label: "Every expert\nwas a beginner!" },
      ],
    },
  },

  "Art & Creativity": {
    1: {
      imageUrl: u("1513364776144-60967b0f800f"),
      emoji: "🎨",
      simpleSummary: "Color theory explains how colors work together to create beautiful art!",
      keyFacts: [
        "Primary colors: Red, Yellow, Blue — they can't be made by mixing other colors 🔴🟡🔵",
        "Secondary colors: mix two primaries — Red + Yellow = Orange, Yellow + Blue = Green.",
        "Warm colors (red, orange, yellow) feel energetic; cool colors (blue, green) feel calm.",
        "Complementary colors sit opposite on the color wheel — they make each other pop!",
      ],
      funFact: "🌟 Ancient Egyptians made blue paint from lapis lazuli — worth more than gold!",
      diagramSteps: [
        { icon: "🔴🟡🔵", label: "Primary colors:\ncan't be mixed!" },
        { icon: "🟠", label: "Red+Yellow\n= Orange 🎉" },
        { icon: "🟢", label: "Yellow+Blue\n= Green 🌿" },
        { icon: "🟣", label: "Red+Blue\n= Purple 💜" },
        { icon: "🌡️", label: "Warm🔥 vs\nCool❄️ colors", color: "green" },
        { icon: "🌈", label: "Infinite colors\nto create!" },
      ],
    },
    2: {
      imageUrl: u("1452860606245-08befc0ff44b"),
      emoji: "✏️",
      simpleSummary: "Drawing is about observation — really LOOKING at what you want to draw before you start!",
      keyFacts: [
        "Start with basic shapes: circles, squares, and triangles hidden in complex objects 🔵🟫",
        "Contour drawing: draw only the outline/edges of an object.",
        "Light and shadow (shading) make flat drawings look three-dimensional 💡",
        "Gesture drawing: capture movement and emotion quickly with loose strokes.",
      ],
      funFact: "🌟 Leonardo da Vinci filled over 7,000 pages of notebooks with drawings!",
      diagramSteps: [
        { icon: "⭕🔺⬛", label: "Step 1:\nbasic shapes" },
        { icon: "✏️", label: "Step 2:\nadd details & lines" },
        { icon: "🌑", label: "Step 3:\nshade dark areas" },
        { icon: "💡", label: "Step 4:\nhighlight bright spots" },
        { icon: "🖼️", label: "Step 5:\nfinished drawing! ✅", color: "green" },
        { icon: "7000📄", label: "Da Vinci:\n7,000 sketchbook pages!" },
      ],
    },
    3: {
      imageUrl: u("1460661419201-fd4cecdf8a8b"),
      emoji: "🖼️",
      simpleSummary: "Composition is HOW you arrange objects in an artwork to guide the viewer's eye!",
      keyFacts: [
        "Rule of thirds: divide the image into 9 equal parts — place subjects on the lines 📐",
        "Foreground, midground, background create depth and distance.",
        "Leading lines: roads, rivers, paths guide the viewer's eye into the image.",
        "Negative space: the empty area around the subject can be just as important!",
      ],
      funFact: "🌟 The Mona Lisa is only 30×21 inches — smaller than most school posters!",
      diagramSteps: [
        { icon: "📐 9", label: "Rule of thirds:\n9 equal squares" },
        { icon: "🏔️", label: "Background:\nfar away things" },
        { icon: "🌳", label: "Midground:\nmiddle distance" },
        { icon: "🌸", label: "Foreground:\nup close details" },
        { icon: "➡️", label: "Leading lines:\nguide the eye!", color: "green" },
        { icon: "⬜", label: "Negative space:\nemptiness matters!" },
      ],
    },
    4: {
      imageUrl: u("1549490349-8643362247b5"),
      emoji: "🏺",
      simpleSummary: "Sculpture is 3D art you can walk around and touch — it exists in real space!",
      keyFacts: [
        "Materials: clay, stone, wood, metal, glass, even recycled objects 🏺",
        "Relief: sculpture that projects from a flat surface (like coins or medals).",
        "Carving: subtractive — removing material. Modeling: additive — building up material.",
        "Installation art: large sculptures that transform an entire space or room.",
      ],
      funFact: "🌟 Michelangelo spent 2 years carving David from a single block of marble!",
      diagramSteps: [
        { icon: "🧱", label: "Material:\nclay, stone, wood, metal" },
        { icon: "✂️ Carve", label: "Carving:\nSUBTRACT material" },
        { icon: "🏺 Model", label: "Modeling:\nADD material on" },
        { icon: "🪙", label: "Relief:\nprojects from surface" },
        { icon: "🏛️", label: "Installation:\ntransforms a whole room!", color: "green" },
        { icon: "2yrs🔨", label: "David: 2 years\nof Michelangelo!" },
      ],
    },
    5: {
      imageUrl: u("1618005198919-d3d4b5a92ead"),
      emoji: "🎭",
      simpleSummary: "Art movements show how artists changed their style to reflect the world around them!",
      keyFacts: [
        "Impressionism: captures light and mood, not precise details (Monet's water lilies) 🌊",
        "Cubism: shows objects from multiple angles at once (Picasso) 🎭",
        "Pop Art: uses images from popular culture and advertising (Andy Warhol's soup cans).",
        "Abstract art: uses shapes, colors, and forms without depicting real objects.",
      ],
      funFact: "🌟 Van Gogh only sold ONE painting during his lifetime — today they sell for $100 million+!",
      diagramSteps: [
        { icon: "🌊", label: "Impressionism:\nblurry & dreamy light" },
        { icon: "🔷", label: "Cubism:\nmultiple angles at once" },
        { icon: "🥫", label: "Pop Art:\nbold & from culture" },
        { icon: "⬛🔵", label: "Abstract:\nshapes & feelings" },
        { icon: "🎨", label: "Surrealism:\ndream-like worlds!", color: "green" },
        { icon: "100M$", label: "Van Gogh: 1 sale\nin his life → now $100M!" },
      ],
    },
    6: {
      imageUrl: u("1493225457124-a3eb161ffa5f"),
      emoji: "🎵",
      simpleSummary: "Music is organized sound — rhythm, melody, and harmony work together to express emotions!",
      keyFacts: [
        "Rhythm: the pattern of beats — it makes you want to move! 🥁",
        "Melody: a sequence of notes that create a tune you can hum.",
        "Harmony: multiple notes played together that sound pleasing.",
        "Tempo: how fast or slow the music plays (largo = slow, presto = very fast) 🎻",
      ],
      funFact: "🌟 Beethoven composed great symphonies after becoming completely deaf — he felt vibrations!",
      diagramSteps: [
        { icon: "🥁", label: "Rhythm:\nthe heartbeat beat" },
        { icon: "🎵", label: "Melody:\nthe tune you hum" },
        { icon: "🎶", label: "Harmony:\nnotes together" },
        { icon: "⏩⏪", label: "Tempo:\nfast vs slow" },
        { icon: "🔊", label: "Dynamics:\nsoft vs LOUD!", color: "green" },
        { icon: "🎻", label: "Beethoven: deaf\nbut felt vibrations!" },
      ],
    },
    7: {
      imageUrl: u("1594389615253-47a0ac2c32a4"),
      emoji: "📸",
      simpleSummary: "Photography captures a moment in time — light, composition, and timing make a great photo!",
      keyFacts: [
        "A camera lens focuses light onto a sensor or film to create an image 📷",
        "Golden hour: just after sunrise and before sunset gives the most beautiful light.",
        "Rule of thirds works for photography too — don't always center your subject!",
        "Macro photography: extreme close-ups reveal the hidden beauty in tiny things 🔍",
      ],
      funFact: "🌟 The oldest surviving photograph was taken in 1826 and required an 8-HOUR exposure!",
      diagramSteps: [
        { icon: "☀️", label: "Light:\nenters the lens" },
        { icon: "📷", label: "Lens:\nfocuses the light" },
        { icon: "💾", label: "Sensor:\ncaptures the image" },
        { icon: "📐", label: "Rule of thirds:\ndon't center!" },
        { icon: "🌅", label: "Golden hour:\nbest natural light!", color: "green" },
        { icon: "8hr⏱️", label: "First photo: 1826,\n8-hour exposure!" },
      ],
    },
    8: {
      imageUrl: u("1565008447742-97f6f38c985c"),
      emoji: "🎬",
      simpleSummary: "Animation brings drawings to life by showing many still images very quickly!",
      keyFacts: [
        "24 frames per second: animation requires 24 different drawings for just 1 second! 🎬",
        "Keyframes: the most important positions — in-between frames fill the gaps.",
        "12 principles include squash/stretch, anticipation, and follow-through.",
        "Pixar's Toy Story (1995) was the first fully computer-animated feature film 🤖",
      ],
      funFact: "🌟 Each frame of the movie 'Brave' took 100+ computers an average of 100 hours to render!",
      diagramSteps: [
        { icon: "🖼️ 1", label: "Frame 1:\nposition A" },
        { icon: "🖼️ 2", label: "Frame 2:\nslightly moved" },
        { icon: "🖼️ 3", label: "Frame 3:\nmore movement" },
        { icon: "🖼️ 24", label: "Frame 24:\nend position" },
        { icon: "🎬×24", label: "24 per second\n= smooth! ✨", color: "green" },
        { icon: "100hrs", label: "Brave: 100 computers,\n100 hrs per frame!" },
      ],
    },
    9: {
      imageUrl: u("1541961017774-22349e4a1262"),
      emoji: "🖌️",
      simpleSummary: "Digital art uses computers and software to create artwork — the tools are endless!",
      keyFacts: [
        "Drawing tablets let artists draw naturally with a stylus on a pressure-sensitive surface.",
        "Layers: work on different parts of your artwork separately without ruining the rest 📑",
        "Raster art (Photoshop): made of pixels. Vector art: made of paths — scales perfectly!",
        "Digital art can be printed, shared online, or animated — endless possibilities.",
      ],
      funFact: "🌟 The first computer-generated image was created in 1960 — it was just random triangles!",
      diagramSteps: [
        { icon: "🖊️ Tablet", label: "Drawing tablet:\npressure sensitive" },
        { icon: "📑 Layers", label: "Layers:\nwork separately" },
        { icon: "🔵 Raster", label: "Raster (pixels):\nPhotoshop style" },
        { icon: "🔷 Vector", label: "Vector (paths):\nscales perfectly!" },
        { icon: "🌐 Share", label: "Share anywhere\nonline! 🎉", color: "green" },
        { icon: "🔺 1960", label: "First CG image:\n1960 — just triangles!" },
      ],
    },
    10: {
      imageUrl: u("1578662996442-48f60103fc96"),
      emoji: "🎪",
      simpleSummary: "Your creativity is unique — art is about expressing YOUR ideas and seeing the world your way!",
      keyFacts: [
        "There are no mistakes in art — unexpected results can lead to amazing discoveries! 🎨",
        "Mix different mediums: watercolor + pencil + collage = your unique style.",
        "Study artists you admire, then add your own twist to develop your voice.",
        "Share your art! Art connects people across language and cultural barriers 🌍",
      ],
      funFact: "🌟 Matisse created some of his most famous work while bedridden in his 80s using scissors and paper!",
      diagramSteps: [
        { icon: "💡", label: "Your unique\nartistic vision" },
        { icon: "🎨", label: "Choose your\nmedium & tools" },
        { icon: "✨", label: "Pour your\nfeelings in" },
        { icon: "🔄", label: "Experiment:\nno mistakes in art!" },
        { icon: "🌍", label: "Share your art\nwith the world!", color: "green" },
        { icon: "🌟", label: "YOUR creativity\nis a superpower!" },
      ],
    },
  },
};

const DEFAULT_MEDIA: LessonMedia = {
  imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&fit=crop",
  emoji: "📚",
  simpleSummary: "This lesson explores a fascinating topic — read carefully and you'll be an expert!",
  keyFacts: [
    "Pay attention to the key vocabulary words in bold.",
    "Try to make connections to things you already know.",
    "Take notes as you read — it helps you remember!",
    "Ask questions when something is unclear — curiosity is a superpower!",
  ],
  funFact: "🌟 The human brain can form new connections at any age — you're literally reshaping your brain right now by learning!",
  diagramSteps: [
    { icon: "📖", label: "Step 1:\nRead carefully" },
    { icon: "❓", label: "Step 2:\nAsk questions" },
    { icon: "💡", label: "Step 3:\nFind key ideas" },
    { icon: "✍️", label: "Step 4:\nTake notes" },
    { icon: "✅", label: "Step 5:\nYou learned it!", color: "green" },
    { icon: "🔁", label: "Repeat:\nspaced repetition!" },
  ],
};

export function getLessonMedia(courseTitle: string, lessonOrder: number): LessonMedia {
  return LESSON_MEDIA[courseTitle]?.[lessonOrder] ?? DEFAULT_MEDIA;
}
