export interface LessonMedia {
  videoId: string;
  imageUrl: string;
  emoji: string;
  simpleSummary: string;
  keyFacts: string[];
  funFact: string;
}

// YouTube video IDs + Unsplash images for every lesson (6 courses × 10 lessons = 60)
const LESSON_MEDIA: Record<string, Record<number, LessonMedia>> = {
  "Math Adventures": {
    1: {
      videoId: "AuX7nPBqDts",
      imageUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&fit=crop",
      emoji: "➕",
      simpleSummary: "Addition means putting two groups together to find out how many there are in total!",
      keyFacts: [
        "2 + 3 means you have 2 things, then you add 3 more — now you have 5! 🎉",
        "When you add 0 to any number, the number stays the same (5 + 0 = 5).",
        "You can add numbers in any order: 3 + 4 is the same as 4 + 3.",
        "Adding is like counting forward on a number line ➡️",
      ],
      funFact: "🌟 Every time you count objects, you're already using addition!",
    },
    2: {
      videoId: "Wm7N-OfSFeo",
      imageUrl: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=800&fit=crop",
      emoji: "➖",
      simpleSummary: "Subtraction is finding out how many are left when you take some away!",
      keyFacts: [
        "7 – 3 means: start with 7, take away 3, you have 4 left 🐘",
        "When you subtract 0, nothing changes (8 – 0 = 8).",
        "Subtraction is the opposite of addition — they undo each other!",
        "Subtracting on a number line means moving backwards ⬅️",
      ],
      funFact: "🌟 If you eat 3 cookies from a pack of 10, you have 7 left — that's subtraction!",
    },
    3: {
      videoId: "mvOkMYCygps",
      imageUrl: "https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=800&fit=crop",
      emoji: "✖️",
      simpleSummary: "Multiplication is a fast way to add the same number over and over again!",
      keyFacts: [
        "3 × 4 means adding 3 four times: 3 + 3 + 3 + 3 = 12 🚀",
        "Any number times 1 stays the same (5 × 1 = 5).",
        "Any number times 0 equals 0 (99 × 0 = 0).",
        "The order doesn't matter: 2 × 6 = 6 × 2 = 12.",
      ],
      funFact: "🌟 If 4 friends each have 3 balloons, that's 4 × 3 = 12 balloons total!",
    },
    4: {
      videoId: "F8RNMf3QTDI",
      imageUrl: "https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=800&fit=crop",
      emoji: "➗",
      simpleSummary: "Division means splitting a group into equal parts to see how many each part gets!",
      keyFacts: [
        "12 ÷ 3 = 4 means 12 things split into 3 equal groups gives 4 each 🍕",
        "Division is the opposite of multiplication.",
        "Any number divided by 1 stays the same (9 ÷ 1 = 9).",
        "You can't divide by zero — it doesn't make sense in math!",
      ],
      funFact: "🌟 Sharing 8 candies equally with 4 friends? That's 8 ÷ 4 = 2 each!",
    },
    5: {
      videoId: "n0FZhQ_GkKw",
      imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&fit=crop",
      emoji: "🍕",
      simpleSummary: "Fractions show parts of a whole — like slices of pizza!",
      keyFacts: [
        "1/2 means one part out of two equal pieces 🍕",
        "The number on top (numerator) tells how many parts you have.",
        "The number on bottom (denominator) tells how many total equal parts.",
        "1/4 + 1/4 + 1/4 + 1/4 = 1 whole!",
      ],
      funFact: "🌟 When you eat half a pizza, you ate 1/2 of it — that's a fraction!",
    },
    6: {
      videoId: "SqW0yZzInNA",
      imageUrl: "https://images.unsplash.com/photo-1588854337115-1c67d9247e4d?w=800&fit=crop",
      emoji: "📐",
      simpleSummary: "Geometry is about shapes — their sides, corners, and how they fit in space!",
      keyFacts: [
        "A triangle has 3 sides and 3 corners 🔺",
        "A square has 4 equal sides and 4 square corners.",
        "A circle has no sides — it's a perfect round shape ⭕",
        "Shapes are everywhere around us: books are rectangles, clocks are circles!",
      ],
      funFact: "🌟 Honeybees build their honeycombs in perfect hexagons — 6 sides each!",
    },
    7: {
      videoId: "RD0_6YZIxL0",
      imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&fit=crop",
      emoji: "📏",
      simpleSummary: "Measurement helps us compare sizes, weights, and distances!",
      keyFacts: [
        "We use centimeters (cm) and meters (m) to measure length 📏",
        "1 meter = 100 centimeters. A door is about 2 meters tall!",
        "Kilograms (kg) measure how heavy something is.",
        "Liters measure how much liquid fits in a container.",
      ],
      funFact: "🌟 Your thumb is about 1 centimeter wide — that's how ancient people measured inches!",
    },
    8: {
      videoId: "Fy1UjGXnGIY",
      imageUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=800&fit=crop",
      emoji: "🔢",
      simpleSummary: "Number patterns are sequences that follow a rule — can you find it?",
      keyFacts: [
        "2, 4, 6, 8… this pattern adds 2 each time (even numbers!).",
        "1, 3, 9, 27… this pattern multiplies by 3 each time.",
        "Patterns are everywhere: tiles, music, and even nature!",
        "Finding the rule lets you predict what comes next.",
      ],
      funFact: "🌟 The Fibonacci sequence (1, 1, 2, 3, 5, 8, 13…) appears in sunflowers and seashells!",
    },
    9: {
      videoId: "1aNpSVKEbvU",
      imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&fit=crop",
      emoji: "🧩",
      simpleSummary: "Word problems use math to solve real-life situations — read carefully!",
      keyFacts: [
        "First, find the numbers in the problem. Then decide: add, subtract, multiply, or divide?",
        "Draw a picture or diagram to help visualize the problem 🖼️",
        "Keywords: 'in all' / 'total' → add; 'left over' → subtract; 'each' → multiply or divide.",
        "Always check your answer by reading the question again!",
      ],
      funFact: "🌟 Ancient Egyptians used word problems 4,000 years ago to build pyramids!",
    },
    10: {
      videoId: "WmVLcj-XKnM",
      imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&fit=crop",
      emoji: "⚡",
      simpleSummary: "Mental math lets you solve problems fast — right in your head!",
      keyFacts: [
        "To add 9, first add 10, then subtract 1. (47 + 9 → 47 + 10 – 1 = 56).",
        "Doubles are easy: 7 + 7 = 14, 8 + 8 = 16 — learn them!",
        "Round to the nearest 10 for quick estimates.",
        "Practice makes you faster — even 5 minutes a day helps!",
      ],
      funFact: "🌟 Mental math champions can multiply 7-digit numbers in their heads!",
    },
  },
  "Science Explorer": {
    1: {
      videoId: "TWz_Z9yLew0",
      imageUrl: "https://images.unsplash.com/photo-1504192010706-dd7f569ee2be?w=800&fit=crop",
      emoji: "💧",
      simpleSummary: "Water travels from oceans to clouds to rain and back again — it never stops!",
      keyFacts: [
        "Evaporation: The sun heats water, turning it into invisible water vapor ☀️",
        "Condensation: Water vapor cools and forms tiny droplets → clouds ☁️",
        "Precipitation: Water falls back as rain, snow, or hail 🌧️",
        "Collection: Water flows back into rivers, lakes, and oceans 🌊",
      ],
      funFact: "🌟 The same water that dinosaurs drank millions of years ago is still cycling around our planet today!",
    },
    2: {
      videoId: "AP-jP7cHDXI",
      imageUrl: "https://images.unsplash.com/photo-1559825481-12a05cc00344?w=800&fit=crop",
      emoji: "🧊",
      simpleSummary: "Matter can be solid, liquid, or gas — and it can change between them!",
      keyFacts: [
        "Solid: particles are tightly packed — keeps its shape (ice, rock, wood) 🪨",
        "Liquid: particles flow — takes the shape of its container (water, juice) 💧",
        "Gas: particles spread out freely — fills all available space (air, steam) 💨",
        "Heat causes matter to melt or evaporate; cold causes it to freeze.",
      ],
      funFact: "🌟 Dry ice is solid CO₂ that turns directly into gas (no liquid stage) — it skips the liquid state!",
    },
    3: {
      videoId: "RnqqGEnKtRc",
      imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&fit=crop",
      emoji: "🌱",
      simpleSummary: "Plants grow from tiny seeds and make their own food using sunlight!",
      keyFacts: [
        "Germination: A seed sprouts when it has water, warmth, and oxygen 🌱",
        "Photosynthesis: Leaves use sunlight + water + CO₂ to make food + oxygen ☀️",
        "Roots absorb water and nutrients from the soil.",
        "Flowers help the plant reproduce — they attract bees and butterflies 🌸",
      ],
      funFact: "🌟 The world's tallest tree (a redwood) is taller than a 35-story building!",
    },
    4: {
      videoId: "nT8FHK8FcaM",
      imageUrl: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&fit=crop",
      emoji: "🦁",
      simpleSummary: "Every animal lives in a habitat perfectly suited to its needs!",
      keyFacts: [
        "Desert animals store water and stay cool (camels, lizards) 🐪",
        "Ocean animals breathe through gills and have streamlined bodies 🐟",
        "Forest animals use camouflage to hide in trees and leaves 🦎",
        "A habitat provides food, water, shelter, and space 🏠",
      ],
      funFact: "🌟 Polar bears have black skin under their white fur — it helps absorb heat from the sun!",
    },
    5: {
      videoId: "ITbCG9iCe3Y",
      imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&fit=crop",
      emoji: "⚙️",
      simpleSummary: "Simple machines make work easier by changing the direction or size of a force!",
      keyFacts: [
        "Lever: a bar that pivots on a fulcrum — teeter-totters and crowbars 🪨",
        "Wheel & Axle: makes it easier to roll heavy things — cars and wagons 🚗",
        "Pulley: uses a rope and wheel to lift heavy loads — flagpoles 🚩",
        "Inclined Plane: a ramp makes it easier to move things up ⛰️",
      ],
      funFact: "🌟 Ancient Egyptians built the pyramids using simple machines — ramps, sleds, and levers!",
    },
    6: {
      videoId: "0Z0-aRs44Cs",
      imageUrl: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?w=800&fit=crop",
      emoji: "⚡",
      simpleSummary: "Electricity is the flow of tiny particles called electrons through a wire!",
      keyFacts: [
        "Electrons flow from negative (-) to positive (+) in a circuit ⚡",
        "A circuit must be complete (no gaps) for electricity to flow.",
        "Conductors (copper, iron) let electricity through; insulators (rubber, plastic) block it.",
        "Batteries push electrons using chemical energy 🔋",
      ],
      funFact: "🌟 Lightning is electricity jumping from clouds to the ground — a single bolt has 1 billion volts!",
    },
    7: {
      videoId: "2UHS883_P60",
      imageUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&fit=crop",
      emoji: "🌍",
      simpleSummary: "Earth has layers — like a hard-boiled egg — each with its own properties!",
      keyFacts: [
        "Crust: the thin outer layer we live on (0–70 km deep) 🗻",
        "Mantle: hot, slow-moving rock below the crust (~2,900 km thick) 🌋",
        "Outer Core: liquid iron and nickel that creates Earth's magnetic field.",
        "Inner Core: solid iron ball, incredibly hot (about 5,000°C!) 🔥",
      ],
      funFact: "🌟 The Earth's crust is only about 1% of its total volume — most of Earth is the mantle!",
    },
    8: {
      videoId: "yqc9zR5ov5c",
      imageUrl: "https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=800&fit=crop",
      emoji: "🌕",
      simpleSummary: "The Moon orbits Earth, and Earth orbits the Sun — our solar system is enormous!",
      keyFacts: [
        "Earth takes 365 days (1 year) to orbit the Sun ☀️",
        "The Moon takes about 29 days to orbit Earth 🌕",
        "Gravity is the force that keeps planets in orbit.",
        "Our solar system has 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
      ],
      funFact: "🌟 If Earth were the size of a grape, the Sun would be as big as a 6-story building!",
    },
    9: {
      videoId: "IbKDiTMlXpk",
      imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&fit=crop",
      emoji: "🌡️",
      simpleSummary: "Weather is what's happening in the atmosphere right now — it changes every day!",
      keyFacts: [
        "Temperature measures how hot or cold the air is 🌡️",
        "Wind is caused by warm air rising and cool air rushing in.",
        "Clouds form when water vapor condenses around tiny dust particles ☁️",
        "Meteorologists use satellites, radar, and weather stations to forecast weather 📡",
      ],
      funFact: "🌟 A tornado's wind can spin faster than 300 mph — faster than a race car!",
    },
    10: {
      videoId: "mQrlgH97v94",
      imageUrl: "https://images.unsplash.com/photo-1532094349884-543290648cca?w=800&fit=crop",
      emoji: "🧫",
      simpleSummary: "The human body is made of trillions of tiny cells working together like a team!",
      keyFacts: [
        "Cells are the smallest unit of life — too tiny to see without a microscope 🔬",
        "Heart cells pump blood; nerve cells carry messages; muscle cells move your body.",
        "Red blood cells carry oxygen from lungs to every part of your body 🩸",
        "Your body makes millions of new cells every second!",
      ],
      funFact: "🌟 You have about 37 trillion cells in your body — more than all the stars in the Milky Way!",
    },
  },
  "Reading & Writing Stars": {
    1: {
      videoId: "PKbdpU7GWAY",
      imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&fit=crop",
      emoji: "📖",
      simpleSummary: "Every story has characters, a setting, a problem, and a solution!",
      keyFacts: [
        "Characters: the people or animals the story is about 🧑",
        "Setting: where and when the story takes place (a forest, in the past) 🌲",
        "Plot: the events that happen — beginning, middle, end 📚",
        "Theme: the big message or lesson the author wants you to learn.",
      ],
      funFact: "🌟 The world's longest novel (À la recherche du temps perdu) has 1.5 million words — about 9,000 pages!",
    },
    2: {
      videoId: "qFbYNpFkXj0",
      imageUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&fit=crop",
      emoji: "🧠",
      simpleSummary: "Good readers ask questions, make predictions, and connect ideas to understand text!",
      keyFacts: [
        "Main idea: the most important point the text is making 💡",
        "Supporting details: facts and examples that explain the main idea.",
        "Make inferences: use clues + what you know to figure out what's not directly stated.",
        "Summarize: put the key ideas in your own words after reading.",
      ],
      funFact: "🌟 Speed readers can read 1,000+ words per minute — that's a page every 30 seconds!",
    },
    3: {
      videoId: "UF8uR6Z6KLc",
      imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&fit=crop",
      emoji: "✍️",
      simpleSummary: "Good writing has a beginning (hook), middle (details), and end (conclusion)!",
      keyFacts: [
        "Hook: start with something interesting to grab the reader's attention! 🎣",
        "Body paragraphs: each one has a main idea + 2-3 supporting details.",
        "Conclusion: wrap up your ideas and leave the reader thinking.",
        "Revise and edit: always re-read your writing to make it better! ✏️",
      ],
      funFact: "🌟 J.K. Rowling wrote Harry Potter on paper napkins in a café before she could afford a computer!",
    },
    4: {
      videoId: "f1GFR_0V_Ac",
      imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&fit=crop",
      emoji: "🔤",
      simpleSummary: "Grammar rules help us write clearly so readers can understand exactly what we mean!",
      keyFacts: [
        "Noun: a person, place, thing, or idea (cat, school, happiness) 🐱",
        "Verb: an action or state of being (run, is, think) 🏃",
        "Adjective: describes a noun (big, blue, happy) 🎨",
        "A sentence needs at least a subject (noun) and a predicate (verb) to be complete.",
      ],
      funFact: "🌟 The sentence 'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo' is grammatically correct English!",
    },
    5: {
      videoId: "RK9pjY6-f5I",
      imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&fit=crop",
      emoji: "🔡",
      simpleSummary: "Spelling tricks help you remember tricky words — patterns make spelling easier!",
      keyFacts: [
        "i before e except after c (receive, believe) — but there are exceptions!",
        "Silent letters: the 'k' in 'know', the 'b' in 'climb', the 'w' in 'write' 🤫",
        "Compound words: two words join to make one (sunshine = sun + shine) ☀️",
        "Prefixes and suffixes: un + happy = unhappy; play + ful = playful.",
      ],
      funFact: "🌟 The word 'queue' is 80% silent — you only pronounce the letter 'q'!",
    },
    6: {
      videoId: "0enr38yptZo",
      imageUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&fit=crop",
      emoji: "🗣️",
      simpleSummary: "Vocabulary means knowing lots of words — the more you know, the better you read and write!",
      keyFacts: [
        "Context clues: use nearby words in the sentence to guess a word's meaning 🕵️",
        "Synonyms: words with similar meanings (big, large, huge).",
        "Antonyms: words with opposite meanings (hot ↔ cold, fast ↔ slow) 🔄",
        "Root words: 'port' means carry → transport, import, export.",
      ],
      funFact: "🌟 Shakespeare invented over 1,700 English words we still use today — including 'bedroom', 'lonely', and 'generous'!",
    },
    7: {
      videoId: "6qEq3vnFtHk",
      imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&fit=crop",
      emoji: "🎭",
      simpleSummary: "Poetry uses rhythm, rhyme, and vivid images to express feelings and ideas!",
      keyFacts: [
        "Rhyme: words that end with the same sound (cat/hat, moon/tune) 🌙",
        "Rhythm: the beat or flow of words in a poem — like music!",
        "Simile: comparing using 'like' or 'as' (as fast as lightning ⚡)",
        "Metaphor: saying something IS something else (life is a rollercoaster 🎢)",
      ],
      funFact: "🌟 The shortest poem ever written is 'Fleas / Adam / Had'em' — just 3 words and 6 syllables!",
    },
    8: {
      videoId: "mzDeT6JUrFk",
      imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&fit=crop",
      emoji: "📰",
      simpleSummary: "Nonfiction writing shares real facts, opinions, and information about the world!",
      keyFacts: [
        "Fact: something that can be proven true (The Eiffel Tower is in Paris ✅)",
        "Opinion: what someone thinks or believes (Paris is the most beautiful city).",
        "Text features: headings, bold words, captions, and diagrams help readers.",
        "Bias: when a writer favors one side — good readers notice this!",
      ],
      funFact: "🌟 The first newspaper was printed in Germany in 1605 — before that, news spread by word of mouth!",
    },
    9: {
      videoId: "GMoqg_s4Dl4",
      imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&fit=crop",
      emoji: "🖊️",
      simpleSummary: "Persuasive writing tries to convince the reader to agree with your opinion!",
      keyFacts: [
        "State your opinion clearly at the beginning. 💬",
        "Give 3 strong reasons to support your opinion.",
        "Use evidence: facts, statistics, and examples make arguments stronger 📊",
        "Address the other side (counterargument) and explain why you still disagree.",
      ],
      funFact: "🌟 The most persuasive word in English is 'you' — it makes people feel personally involved!",
    },
    10: {
      videoId: "ZyHvNnqq3KM",
      imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=800&fit=crop",
      emoji: "🌐",
      simpleSummary: "Research skills help you find trustworthy information and use it in your writing!",
      keyFacts: [
        "Reliable sources: encyclopedias, textbooks, .gov and .edu websites 📚",
        "Keywords: use specific search words to find exactly what you need.",
        "Note-taking: write down key ideas in your own words — not copy-paste!",
        "Citation: always credit the author/source of information you use.",
      ],
      funFact: "🌟 Wikipedia has over 60 million articles in 300+ languages — but always double-check important facts!",
    },
  },
  "World Geography Quest": {
    1: {
      videoId: "nI7DFGgdQag",
      imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&fit=crop",
      emoji: "🌍",
      simpleSummary: "Earth has 7 continents and 5 oceans — let's explore them all!",
      keyFacts: [
        "7 Continents: Asia, Africa, North America, South America, Antarctica, Europe, Australia 🗺️",
        "5 Oceans: Pacific (largest), Atlantic, Indian, Southern, Arctic (smallest) 🌊",
        "Asia is the largest continent — it has more than half of all Earth's people!",
        "Antarctica is the coldest, driest, and windiest continent — no permanent human population.",
      ],
      funFact: "🌟 The Pacific Ocean is so large you could fit all 7 continents inside it and still have room to spare!",
    },
    2: {
      videoId: "LmOFEFSe1MM",
      imageUrl: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&fit=crop",
      emoji: "🏛️",
      simpleSummary: "There are 195 countries in the world, each with its own capital city and flag!",
      keyFacts: [
        "Russia is the world's largest country — it covers 11 time zones! 🇷🇺",
        "Vatican City is the smallest country — it fits inside the city of Rome 🇻🇦",
        "China and India each have over 1 billion people — the most of any country.",
        "Every country has a flag that represents its history and values 🏳️",
      ],
      funFact: "🌟 The country of Monaco is smaller than New York's Central Park — yet it's one of the richest nations!",
    },
    3: {
      videoId: "1S-MFEgFYbI",
      imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&fit=crop",
      emoji: "🎎",
      simpleSummary: "Every culture around the world has its own unique food, music, clothing, and traditions!",
      keyFacts: [
        "Japan has a tradition called 'hanami' — people gather to admire cherry blossoms 🌸",
        "India celebrates Diwali, the Festival of Lights, with fireworks and oil lamps 🪔",
        "Brazil's Carnival is one of the world's biggest festivals — millions attend! 🎉",
        "Food tells the story of a culture — spices, ingredients, and recipes passed through generations.",
      ],
      funFact: "🌟 There are over 7,000 languages spoken in the world — but only about 23 languages are spoken by half of all people!",
    },
    4: {
      videoId: "9mLdo4uMHMQ",
      imageUrl: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800&fit=crop",
      emoji: "🌡️",
      simpleSummary: "Different parts of Earth have different climates based on their distance from the equator!",
      keyFacts: [
        "Tropical zone (near equator): hot and rainy all year — home to rainforests 🌴",
        "Temperate zone (middle): 4 seasons — spring, summer, autumn, winter ❄️",
        "Polar zone (near poles): freezing cold all year — ice and tundra 🧊",
        "Climate affects what food people grow and how they build their homes.",
      ],
      funFact: "🌟 The Atacama Desert in Chile is the driest place on Earth — some parts haven't had rain in 400 years!",
    },
    5: {
      videoId: "sYB82e40EJ0",
      imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&fit=crop",
      emoji: "🏔️",
      simpleSummary: "Earth's natural wonders show the amazing power of nature — from mountains to waterfalls!",
      keyFacts: [
        "Mount Everest (8,849 m) is the highest point on Earth 🏔️",
        "The Great Barrier Reef in Australia is the world's largest living structure 🐠",
        "The Amazon River carries more water than the next 7 largest rivers combined 🌊",
        "The Northern Lights (aurora borealis) are caused by solar particles hitting Earth's atmosphere ✨",
      ],
      funFact: "🌟 Victoria Falls on the border of Zimbabwe and Zambia is so loud, it can be heard 40 km away!",
    },
    6: {
      videoId: "KVIADVHLxMU",
      imageUrl: "https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=800&fit=crop",
      emoji: "🗺️",
      simpleSummary: "Maps are tools that help us understand where places are in relation to each other!",
      keyFacts: [
        "Latitude lines run east-west; they measure how far north/south you are from the equator.",
        "Longitude lines run north-south; they measure how far east/west from the prime meridian.",
        "The equator (0° latitude) divides Earth into Northern and Southern hemispheres.",
        "GPS satellites in space help phones and cars show maps instantly 📡",
      ],
      funFact: "🌟 Ancient maps from 600 BC showed Babylon at the center of the world — every civilization thought they were at the center!",
    },
    7: {
      videoId: "YbAWny7FV3w",
      imageUrl: "https://images.unsplash.com/photo-1467226632440-65f0b4957563?w=800&fit=crop",
      emoji: "🏙️",
      simpleSummary: "Cities are hubs of culture, trade, and innovation — over half the world's people live in them!",
      keyFacts: [
        "Tokyo, Japan is the world's largest city with over 37 million people! 🗼",
        "Cities develop where there's fresh water, trade routes, or natural resources.",
        "Megacities have 10 million+ people: Mumbai, São Paulo, Mexico City, Cairo 🌆",
        "Urban planning decides how streets, parks, and buildings are organized.",
      ],
      funFact: "🌟 Shanghai's metro system carries more passengers per day than the entire US Amtrak rail network does in a year!",
    },
    8: {
      videoId: "4bm5E4hklxQ",
      imageUrl: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&fit=crop",
      emoji: "🌊",
      simpleSummary: "Oceans cover 71% of Earth's surface and are home to the most diverse ecosystems!",
      keyFacts: [
        "The ocean has 5 zones: sunlight, twilight, midnight, abyssal, and hadal zones 🌊",
        "The Mariana Trench is 11 km deep — deeper than Mount Everest is tall!",
        "Coral reefs cover only 1% of the ocean but house 25% of all marine species.",
        "The ocean produces over half the world's oxygen — mostly from phytoplankton.",
      ],
      funFact: "🌟 We've explored less than 20% of Earth's oceans — more people have walked on the Moon than have been to the deepest part of the sea!",
    },
    9: {
      videoId: "zOj2T-q7HjY",
      imageUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&fit=crop",
      emoji: "🌾",
      simpleSummary: "Agriculture feeds the world — how and where food is grown depends on climate and geography!",
      keyFacts: [
        "Fertile soil + water + sunlight = perfect farming conditions 🌾",
        "Rice feeds more people than any other crop — grown in flooded paddies in Asia.",
        "Greenhouses let farmers grow vegetables even in cold climates 🏡",
        "Modern technology (GPS tractors, drones) makes farms more productive than ever.",
      ],
      funFact: "🌟 The Netherlands — one of the world's smallest countries — is the 2nd largest food exporter on Earth!",
    },
    10: {
      videoId: "VFkQSGyeCWg",
      imageUrl: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&fit=crop",
      emoji: "♻️",
      simpleSummary: "Earth's resources are precious — we must protect the environment for future generations!",
      keyFacts: [
        "Renewable energy: solar, wind, and hydro power can be used forever ☀️",
        "Deforestation destroys habitats and releases stored CO₂ into the atmosphere 🌳",
        "Recycling reduces waste: 1 tonne of recycled paper saves 17 trees.",
        "Climate change is making storms stronger and sea levels higher 🌊",
      ],
      funFact: "🌟 If everyone on Earth lived like the average American, we'd need 5 Earths to support us all!",
    },
  },
  "Coding for Kids": {
    1: {
      videoId: "SzJ46YA_RaA",
      imageUrl: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&fit=crop",
      emoji: "💻",
      simpleSummary: "Programming means giving step-by-step instructions to a computer to solve a problem!",
      keyFacts: [
        "A program is a set of instructions a computer follows exactly as written 📝",
        "Computers do exactly what you tell them — no more, no less!",
        "Programming languages (Python, Scratch, JavaScript) translate human ideas into computer actions.",
        "Bugs are mistakes in code — programmers find and fix them through debugging 🐛",
      ],
      funFact: "🌟 The first computer programmer was Ada Lovelace in 1843 — more than 100 years before the first computer was built!",
    },
    2: {
      videoId: "ltjU26L5t28",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&fit=crop",
      emoji: "🔁",
      simpleSummary: "Sequences are steps in order; loops repeat steps automatically to save time!",
      keyFacts: [
        "Sequence: instructions must be in the right order — step 1, then 2, then 3 📋",
        "Loop: repeat a block of code until a condition is met 🔄",
        "For loop: repeat a fixed number of times (do this 10 times).",
        "While loop: keep repeating while something is true (while hungry: eat).",
      ],
      funFact: "🌟 A video game that runs at 60 frames per second executes its game loop 60 times every second!",
    },
    3: {
      videoId: "m2Ux2PnJe6E",
      imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&fit=crop",
      emoji: "🤔",
      simpleSummary: "Conditions let programs make decisions — like 'if it's raining, bring an umbrella'!",
      keyFacts: [
        "IF statement: 'If this is true, do this' — the program decides based on conditions.",
        "ELSE: 'Otherwise, do this other thing instead' 🔀",
        "Comparison operators: == (equals), > (greater than), < (less than) ⚖️",
        "Boolean: a value that's either TRUE or FALSE — computers love true/false!",
      ],
      funFact: "🌟 All complex AI decisions boil down to thousands of if-else conditions happening in milliseconds!",
    },
    4: {
      videoId: "wY3pRfT8NXs",
      imageUrl: "https://images.unsplash.com/photo-1562813733-b31f71025d54?w=800&fit=crop",
      emoji: "📦",
      simpleSummary: "Variables are like labeled boxes that store information a program can use later!",
      keyFacts: [
        "Variable: a named storage location (score = 0; name = 'Alex') 📦",
        "You can change what's in a variable: score = score + 10.",
        "Data types: numbers (42), text/strings ('hello'), true/false (booleans).",
        "Good variable names describe what they hold: playerScore, not x!",
      ],
      funFact: "🌟 The game Minecraft uses millions of variables to track every block, player, and creature in the world!",
    },
    5: {
      videoId: "HrMCFVUTGis",
      imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&fit=crop",
      emoji: "🎮",
      simpleSummary: "Functions are reusable blocks of code — write once, use many times!",
      keyFacts: [
        "Function: a named block of code that does one specific task 🧩",
        "Call a function by its name to run its code: jump(); or moveRight();",
        "Functions can accept inputs (parameters) and send back results (return values).",
        "Good functions do ONE thing and do it well — makes code easier to understand.",
      ],
      funFact: "🌟 The operating system on your phone has millions of functions all working together — right now!",
    },
    6: {
      videoId: "9SjQKT2PjWk",
      imageUrl: "https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=800&fit=crop",
      emoji: "🌐",
      simpleSummary: "The internet connects billions of computers around the world to share information instantly!",
      keyFacts: [
        "Data travels as packets — small chunks sent separately and reassembled 📦",
        "IP address: a unique number that identifies every device on the internet (like a home address).",
        "HTML builds the structure of web pages; CSS makes them look pretty 🎨",
        "Servers are powerful computers that store and send websites when you visit them.",
      ],
      funFact: "🌟 Every minute, humans upload 500 hours of video to YouTube and send 300 million emails!",
    },
    7: {
      videoId: "E9JRHaGG4K4",
      imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&fit=crop",
      emoji: "🤖",
      simpleSummary: "Artificial Intelligence teaches computers to learn from data and make smart decisions!",
      keyFacts: [
        "Machine learning: computers improve through practice with lots of data 📊",
        "Neural networks: inspired by how the human brain processes information 🧠",
        "AI can recognize faces, translate languages, and beat humans at chess.",
        "The more data AI trains on, the more accurate and useful it becomes.",
      ],
      funFact: "🌟 AlphaGo (an AI) learned to play the game Go by studying 30 million moves — then beat the world champion!",
    },
    8: {
      videoId: "GE3JOFwTxeI",
      imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&fit=crop",
      emoji: "🔒",
      simpleSummary: "Cybersecurity protects computers and information from hackers and bad actors!",
      keyFacts: [
        "Strong passwords use uppercase, lowercase, numbers, and symbols 🔐",
        "Encryption scrambles data so only authorized people can read it.",
        "Phishing: fake emails or websites that trick you into giving away private info 🎣",
        "Always update software — patches fix security holes that hackers exploit.",
      ],
      funFact: "🌟 Over 2,000 cyberattacks happen every day — that's one attack every 39 seconds somewhere in the world!",
    },
    9: {
      videoId: "TkpWxKBtJYU",
      imageUrl: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&fit=crop",
      emoji: "📱",
      simpleSummary: "Apps are programs designed to run on specific devices — making computers useful for everyone!",
      keyFacts: [
        "App = application — a program built for a specific purpose (camera, maps, games) 📱",
        "Mobile apps run on phones; web apps run in browsers; desktop apps run on computers.",
        "The App Store and Google Play each have over 3 million apps available!",
        "App development: design → code → test → launch → improve based on feedback.",
      ],
      funFact: "🌟 Instagram was built by just 13 people — and sold to Facebook for $1 billion just 18 months after launch!",
    },
    10: {
      videoId: "qABGqIosCBE",
      imageUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&fit=crop",
      emoji: "🚀",
      simpleSummary: "Your first project! Put it all together — variables, loops, conditions, and functions!",
      keyFacts: [
        "Start small: a simple game might just need 50 lines of code! 🎮",
        "Plan first: sketch out what you want to build before writing code 📝",
        "Test often: run your code after every small change to catch bugs early.",
        "Share your work: showing others your project helps you improve and inspires them!",
      ],
      funFact: "🌟 Minecraft was created by just one person (Markus 'Notch' Persson) and became one of the best-selling games ever!",
    },
  },
  "Art & Creativity": {
    1: {
      videoId: "8mXNHUiK5as",
      imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&fit=crop",
      emoji: "🎨",
      simpleSummary: "Color theory explains how colors work together to create beautiful art!",
      keyFacts: [
        "Primary colors: Red, Yellow, Blue — they can't be made by mixing other colors 🔴🟡🔵",
        "Secondary colors: mix two primaries — Red + Yellow = Orange, Yellow + Blue = Green.",
        "Warm colors (red, orange, yellow) feel energetic; cool colors (blue, green) feel calm.",
        "Complementary colors sit opposite on the color wheel — they make each other pop!",
      ],
      funFact: "🌟 Ancient Egyptians made blue paint from lapis lazuli — a gemstone so rare it was worth more than gold!",
    },
    2: {
      videoId: "eGKiqKP3MDs",
      imageUrl: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&fit=crop",
      emoji: "✏️",
      simpleSummary: "Drawing is about observation — really LOOKING at what you want to draw before you start!",
      keyFacts: [
        "Start with basic shapes: circles, squares, and triangles hidden in complex objects 🔵🟫",
        "Contour drawing: draw only the outline/edges of an object.",
        "Light and shadow (shading) make flat drawings look three-dimensional 💡",
        "Gesture drawing: capture movement and emotion quickly with loose strokes.",
      ],
      funFact: "🌟 Leonardo da Vinci filled over 7,000 pages of notebooks with drawings and observations — including flying machines 500 years before airplanes!",
    },
    3: {
      videoId: "bG7-6ylH0k0",
      imageUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&fit=crop",
      emoji: "🖼️",
      simpleSummary: "Composition is HOW you arrange objects in an artwork to guide the viewer's eye!",
      keyFacts: [
        "Rule of thirds: divide the image into 9 equal parts — place subjects on the lines 📐",
        "Foreground, midground, background create depth and distance.",
        "Leading lines: roads, rivers, paths guide the viewer's eye into the image.",
        "Negative space: the empty area around the subject can be just as important!",
      ],
      funFact: "🌟 The Mona Lisa is only 30×21 inches — smaller than most school posters — yet it's the world's most famous painting!",
    },
    4: {
      videoId: "rBvCfSW3Yxo",
      imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&fit=crop",
      emoji: "🏺",
      simpleSummary: "Sculpture is 3D art you can walk around and touch — it exists in real space!",
      keyFacts: [
        "Materials: clay, stone, wood, metal, glass, even recycled objects 🏺",
        "Relief: sculpture that projects from a flat surface (like coins or medals).",
        "Carving: subtractive — removing material. Modeling: additive — building up material.",
        "Installation art: large sculptures that transform an entire space or room.",
      ],
      funFact: "🌟 Michelangelo spent 2 years carving David out of a single block of marble that other sculptors had rejected as flawed!",
    },
    5: {
      videoId: "PaVQCFSFNTo",
      imageUrl: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=800&fit=crop",
      emoji: "🎭",
      simpleSummary: "Art movements show how artists changed their style to reflect the world around them!",
      keyFacts: [
        "Impressionism: captures light and mood, not precise details (Monet's water lilies) 🌊",
        "Cubism: shows objects from multiple angles at once (Picasso) 🎭",
        "Pop Art: uses images from popular culture and advertising (Andy Warhol's soup cans).",
        "Abstract art: uses shapes, colors, and forms without depicting real objects.",
      ],
      funFact: "🌟 Van Gogh only sold ONE painting during his lifetime — today his works sell for over $100 million each!",
    },
    6: {
      videoId: "YsRZtbpBoiU",
      imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&fit=crop",
      emoji: "🎵",
      simpleSummary: "Music is organized sound — rhythm, melody, and harmony work together to express emotions!",
      keyFacts: [
        "Rhythm: the pattern of beats — it makes you want to move! 🥁",
        "Melody: a sequence of notes that create a tune you can hum.",
        "Harmony: multiple notes played together that sound pleasing.",
        "Tempo: how fast or slow the music plays (largo = slow, presto = very fast) 🎻",
      ],
      funFact: "🌟 Beethoven composed some of his greatest symphonies after becoming completely deaf — he felt vibrations through the floor!",
    },
    7: {
      videoId: "sSpdAsGpPT4",
      imageUrl: "https://images.unsplash.com/photo-1594389615253-47a0ac2c32a4?w=800&fit=crop",
      emoji: "📸",
      simpleSummary: "Photography captures a moment in time — light, composition, and timing make a great photo!",
      keyFacts: [
        "A camera lens focuses light onto a sensor or film to create an image 📷",
        "Golden hour: just after sunrise and before sunset gives the most beautiful, warm light.",
        "Rule of thirds works for photography too — don't always center your subject!",
        "Macro photography: extreme close-ups reveal the hidden beauty in tiny things 🔍",
      ],
      funFact: "🌟 The world's oldest surviving photograph was taken in 1826 and required an 8-HOUR exposure time — today phones take photos in 1/1000th of a second!",
    },
    8: {
      videoId: "OJPiL1m2UuY",
      imageUrl: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&fit=crop",
      emoji: "🎬",
      simpleSummary: "Animation brings drawings to life by showing many still images very quickly!",
      keyFacts: [
        "24 frames per second: animation requires 24 different drawings for just 1 second of movement! 🎬",
        "Keyframes: the most important positions in an animation — the in-between frames fill the gaps.",
        "12 principles of animation include squash/stretch, anticipation, and follow-through.",
        "Pixar's Toy Story (1995) was the first fully computer-animated feature film 🤖",
      ],
      funFact: "🌟 Each frame of the movie 'Brave' took 100+ computers working together for an average of 100 hours to render!",
    },
    9: {
      videoId: "vBmQH-VXBU0",
      imageUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&fit=crop",
      emoji: "🖌️",
      simpleSummary: "Digital art uses computers and software to create artwork — the tools are endless!",
      keyFacts: [
        "Drawing tablets let artists draw naturally with a stylus on a pressure-sensitive surface.",
        "Layers: work on different parts of your artwork separately without ruining the rest 📑",
        "Raster art (Photoshop): made of pixels. Vector art (Illustrator): made of paths — scales perfectly!",
        "Digital art can be printed, shared online, or animated — endless possibilities.",
      ],
      funFact: "🌟 The first computer-generated image was created in 1960 by a researcher who wanted to test if computers could display shapes — it was just some random triangles!",
    },
    10: {
      videoId: "YtkjvbTnEjA",
      imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&fit=crop",
      emoji: "🎪",
      simpleSummary: "Your creativity is unique — art is about expressing YOUR ideas and seeing the world your way!",
      keyFacts: [
        "There are no mistakes in art — unexpected results can lead to amazing discoveries! 🎨",
        "Mix different mediums: watercolor + pencil + collage = your unique style.",
        "Study artists you admire, then add your own twist to develop your voice.",
        "Share your art! Art connects people across language and cultural barriers 🌍",
      ],
      funFact: "🌟 Henri Matisse, one of the greatest artists ever, created some of his most famous work while bedridden in his 80s using scissors and colored paper!",
    },
  },
};

const DEFAULT_MEDIA: LessonMedia = {
  videoId: "",
  imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&fit=crop",
  emoji: "📚",
  simpleSummary: "This lesson explores a fascinating topic — read carefully and you'll be an expert!",
  keyFacts: [
    "Pay attention to the key vocabulary words in bold.",
    "Try to make connections to things you already know.",
    "Take notes as you read — it helps you remember!",
    "Ask questions when something is unclear — curiosity is a superpower!",
  ],
  funFact: "🌟 The human brain can form new connections at any age — you're literally reshaping your brain right now by learning!",
};

export function getLessonMedia(courseTitle: string, lessonOrder: number): LessonMedia {
  return LESSON_MEDIA[courseTitle]?.[lessonOrder] ?? DEFAULT_MEDIA;
}
